// Sample JLPT-style content for all five levels (N5 -> N1).
//
// IMPORTANT: this is a representative sample for demoing the product, not the
// full JLPT syllabus. Real N5-N1 coverage runs to several thousand vocabulary
// items, ~200-600 grammar patterns, and licensed listening audio per level.
// Swap this file (or feed the same shape into the DB) once real curriculum
// content / a licensed content partner is in place.

export type LevelCode = "N5" | "N4" | "N3" | "N2" | "N1";

export const LEVELS: { id: LevelCode; nameJa: string; nameEn: string; sortOrder: number }[] = [
  { id: "N5", nameJa: "N5(入門)", nameEn: "N5 — Beginner", sortOrder: 1 },
  { id: "N4", nameJa: "N4(初級)", nameEn: "N4 — Elementary", sortOrder: 2 },
  { id: "N3", nameJa: "N3(中級)", nameEn: "N3 — Intermediate", sortOrder: 3 },
  { id: "N2", nameJa: "N2(中上級)", nameEn: "N2 — Upper Intermediate", sortOrder: 4 },
  { id: "N1", nameJa: "N1(上級)", nameEn: "N1 — Advanced", sortOrder: 5 },
];

export interface VocabSeed {
  term: string;
  reading: string;
  meaningJa: string;
  meaningEn: string;
  example: string;
}

export interface GrammarSeed {
  pattern: string;
  meaningEn: string;
  example: string;
}

export type QuestionCategory = "vocabulary" | "grammar" | "listening" | "reading";

export interface QuestionSeed {
  category: QuestionCategory;
  prompt: string;
  choices: string[];
  correctIndex: number;
  explanation: string;
}

interface LevelContent {
  vocab: VocabSeed[];
  grammar: GrammarSeed[];
  questions: QuestionSeed[];
}

export const CONTENT: Record<LevelCode, LevelContent> = {
  N5: {
    vocab: [
      { term: "食べる", reading: "たべる", meaningJa: "食事をする", meaningEn: "to eat", example: "朝ごはんを食べます。" },
      { term: "学校", reading: "がっこう", meaningJa: "勉強するところ", meaningEn: "school", example: "毎日学校へ行きます。" },
      { term: "水", reading: "みず", meaningJa: "飲み物", meaningEn: "water", example: "水を飲みます。" },
      { term: "大きい", reading: "おおきい", meaningJa: "サイズが大きい", meaningEn: "big", example: "これは大きい犬です。" },
      { term: "友達", reading: "ともだち", meaningJa: "仲がいい人", meaningEn: "friend", example: "友達と遊びます。" },
      { term: "毎日", reading: "まいにち", meaningJa: "日々", meaningEn: "every day", example: "毎日日本語を勉強します。" },
      { term: "電車", reading: "でんしゃ", meaningJa: "乗り物", meaningEn: "train", example: "電車で会社に行きます。" },
      { term: "忙しい", reading: "いそがしい", meaningJa: "時間がない", meaningEn: "busy", example: "今週はとても忙しいです。" },
      // --- Expanded N5 vocabulary (round 1 of the content-volume expansion) ---
      // Sourced from elzup/jlpt-word-list (MIT license, derived from the
      // widely-cited tanos.co.uk JLPT vocabulary classification), evenly
      // sampled to ~150 words. meaningJa/example authored for this app;
      // translations for all 10 non-English languages live in translations.ts.
      { term: "ああ", reading: "ああ", meaningJa: "驚いたときに言う言葉", meaningEn: "Ah!, Oh!", example: "ああ、わかりました。" },
      { term: "赤", reading: "あか", meaningJa: "りんごのような色", meaningEn: "red", example: "赤が好きです。" },
      { term: "開ける", reading: "あける", meaningJa: "しまっているものを開くこと", meaningEn: "to open (v.t.)", example: "窓を開けます。" },
      { term: "足", reading: "あし", meaningJa: "歩くときに使う体の部分", meaningEn: "foot; leg", example: "足が痛いです。" },
      { term: "暖かい", reading: "あたたかい", meaningJa: "寒くなくて気持ちいい", meaningEn: "warm", example: "今日は暖かいです。" },
      { term: "熱い", reading: "あつい", meaningJa: "温度が高いこと", meaningEn: "hot (objects)", example: "このコーヒーは熱いです。" },
      { term: "兄", reading: "あに", meaningJa: "年上の男のきょうだい", meaningEn: "(my) older brother (humble)", example: "兄は会社員です。" },
      { term: "危ない", reading: "あぶない", meaningJa: "けがをするかもしれない", meaningEn: "dangerous, critical", example: "そこは危ないですよ。" },
      { term: "飴", reading: "あめ", meaningJa: "甘いお菓子", meaningEn: "(hard) candy", example: "飴を一つください。" },
      { term: "あれ", reading: "あれ", meaningJa: "遠くにある物を指す言葉", meaningEn: "that one (over there)", example: "あれは私の車です。" },
      { term: "いかが", reading: "いかが", meaningJa: "「どう」の丁寧な言い方", meaningEn: "how, in what way", example: "お茶はいかがですか。" },
      { term: "池", reading: "いけ", meaningJa: "小さい水の場所", meaningEn: "pond", example: "公園に池があります。" },
      { term: "一", reading: "いち", meaningJa: "数字のいち", meaningEn: "one", example: "一から十まで数えます。" },
      { term: "一緒", reading: "いっしょ", meaningJa: "みんなで同じことをする", meaningEn: "together", example: "友達と一緒に映画を見ます。" },
      { term: "意味", reading: "いみ", meaningJa: "言葉が表すこと", meaningEn: "meaning, significance", example: "この言葉の意味が分かりません。" },
      { term: "居る", reading: "いる", meaningJa: "人や動物がそこにいること", meaningEn: "(humble) to be (animate), to exist", example: "教室に学生がいます。" },
      { term: "上", reading: "うえ", meaningJa: "物の一番高いところ", meaningEn: "above (up, top, etc.), over, on top of", example: "机の上に本があります。" },
      { term: "うち", reading: "うち", meaningJa: "自分が住んでいる家", meaningEn: "home; house; my place", example: "今日はうちにいます。" },
      { term: "上着", reading: "うわぎ", meaningJa: "外に着る服", meaningEn: "coat, jacket", example: "寒いので上着を着ます。" },
      { term: "英語", reading: "えいご", meaningJa: "イギリスやアメリカの言葉", meaningEn: "English (language)", example: "毎日英語を勉強しています。" },
      { term: "鉛筆", reading: "えんぴつ", meaningJa: "字を書く道具", meaningEn: "pencil", example: "鉛筆で名前を書きます。" },
      { term: "大きな", reading: "おおきな", meaningJa: "サイズが大きい様子", meaningEn: "big", example: "大きな犬がいます。" },
      { term: "お金", reading: "おかね", meaningJa: "物を買うときに使う物", meaningEn: "money", example: "お金がありません。" },
      { term: "お皿", reading: "おさら", meaningJa: "食べ物を乗せる物", meaningEn: "plate, dish", example: "お皿を洗います。" },
      { term: "遅い", reading: "おそい", meaningJa: "時間がかかること", meaningEn: "slow; (to be) late", example: "バスが遅いです。" },
      { term: "男", reading: "おとこ", meaningJa: "男性である人", meaningEn: "man, male", example: "あの男の人は先生です。" },
      { term: "大人", reading: "おとな", meaningJa: "成長した人", meaningEn: "adult", example: "大人になったら働きます。" },
      { term: "伯母さん", reading: "おばさん", meaningJa: "父や母の姉や妹", meaningEn: "aunt", example: "伯母さんに会いに行きます。" },
      { term: "おまわりさん", reading: "おまわりさん", meaningJa: "警察の人を呼ぶ言葉", meaningEn: "policeman (friendly term)", example: "おまわりさんに道を聞きました。" },
      { term: "終る", reading: "おわる", meaningJa: "物事が終わること", meaningEn: "to finish, to close", example: "仕事は五時に終わります。" },
      { term: "～回", reading: "～かい", meaningJa: "回数を数える言葉", meaningEn: "counter for occurrences (~ times)", example: "一日に三回薬を飲みます。" },
      { term: "階段", reading: "かいだん", meaningJa: "上ったり下りたりする道", meaningEn: "stairs", example: "階段を上ります。" },
      { term: "顔", reading: "かお", meaningJa: "目や口がある体の部分", meaningEn: "face (body part)", example: "顔を洗います。" },
      { term: "学生", reading: "がくせい", meaningJa: "勉強している人", meaningEn: "student", example: "私は大学の学生です。" },
      { term: "貸す", reading: "かす", meaningJa: "物を人に使わせること", meaningEn: "to lend", example: "友達に本を貸します。" },
      { term: "片仮名", reading: "かたかな", meaningJa: "日本語の文字の一つ", meaningEn: "katakana", example: "外国の言葉は片仮名で書きます。" },
      { term: "角", reading: "かど", meaningJa: "物の端が曲がる所", meaningEn: "corner (e.g., desk, pavement)", example: "角を右に曲がります。" },
      { term: "紙", reading: "かみ", meaningJa: "字を書く薄い物", meaningEn: "paper", example: "紙に絵を描きます。" },
      { term: "借りる", reading: "かりる", meaningJa: "人から物を使わせてもらう", meaningEn: "to borrow, to owe", example: "図書館で本を借ります。" },
      { term: "川", reading: "かわ", meaningJa: "水が流れる所", meaningEn: "river", example: "川で魚を見ました。" },
      { term: "黄色", reading: "きいろ", meaningJa: "バナナのような色", meaningEn: "yellow", example: "黄色が好きです。" },
      { term: "北", reading: "きた", meaningJa: "方角の一つ", meaningEn: "north", example: "北海道は日本の北にあります。" },
      { term: "切符", reading: "きっぷ", meaningJa: "電車やバスに乗る紙", meaningEn: "a ticket", example: "駅で切符を買います。" },
      { term: "今日", reading: "きょう", meaningJa: "この日のこと", meaningEn: "today, this day", example: "今日は月曜日です。" },
      { term: "嫌い", reading: "きらい", meaningJa: "好きではないこと", meaningEn: "dislike", example: "野菜が嫌いです。" },
      { term: "銀行", reading: "ぎんこう", meaningJa: "お金を預ける所", meaningEn: "bank", example: "銀行でお金を出します。" },
      { term: "口", reading: "くち", meaningJa: "食べたり話したりする部分", meaningEn: "job opening; mouth", example: "口を大きく開けてください。" },
      { term: "曇る", reading: "くもる", meaningJa: "空が雲でおおわれること", meaningEn: "to become cloudy, to become dim", example: "明日は曇るでしょう。" },
      { term: "グラム", reading: "グラム", meaningJa: "重さの単位", meaningEn: "gram", example: "砂糖を100グラム買います。" },
      { term: "警官", reading: "けいかん", meaningJa: "警察の仕事をする人", meaningEn: "police officer", example: "警官が近くにいます。" },
      { term: "月曜日", reading: "げつようび", meaningJa: "一週間の最初の日", meaningEn: "Monday", example: "月曜日に学校へ行きます。" },
      { term: "～語", reading: "～ご", meaningJa: "その国の言葉", meaningEn: "word, language", example: "日本語を勉強しています。" },
      { term: "交番", reading: "こうばん", meaningJa: "警察官がいる小さい建物", meaningEn: "police box", example: "交番で道を聞きました。" },
      { term: "午後", reading: "ごご", meaningJa: "昼から夜までの時間", meaningEn: "afternoon, P.M.", example: "午後三時に会いましょう。" },
      { term: "こちら", reading: "こちら", meaningJa: "この人、この方向", meaningEn: "this person (polite); this way (polite)", example: "こちらは田中さんです。" },
      { term: "言葉", reading: "ことば", meaningJa: "話すときに使うもの", meaningEn: "language; word(s); expression(s)", example: "日本語の言葉を覚えます。" },
      { term: "困る", reading: "こまる", meaningJa: "どうしたらいいか分からない", meaningEn: "to be bothered, to have difficulty", example: "お金がなくて困っています。" },
      { term: "こんな", reading: "こんな", meaningJa: "このような", meaningEn: "such, like this", example: "こんな服が好きです。" },
      { term: "魚", reading: "さかな", meaningJa: "水の中にいる動物", meaningEn: "fish", example: "晩ご飯に魚を食べます。" },
      { term: "差す", reading: "さす", meaningJa: "傘を上に開いて持つ", meaningEn: "to raise (stretch out) hands, to raise (e.g., umbrella)", example: "雨だから傘を差します。" },
      { term: "さ来年", reading: "さらいねん", meaningJa: "来年の次の年", meaningEn: "year after next", example: "さ来年、日本へ行きます。" },
      { term: "～時", reading: "～じ", meaningJa: "時刻を表す言葉", meaningEn: "~ o'clock (time)", example: "七時に起きます。" },
      { term: "仕事", reading: "しごと", meaningJa: "お金をもらってする活動", meaningEn: "work, job, occupation, employment", example: "毎日仕事に行きます。" },
      { term: "七", reading: "しち", meaningJa: "数字の7", meaningEn: "seven", example: "七時に会いましょう。" },
      { term: "字引", reading: "じびき", meaningJa: "言葉の意味を調べる本", meaningEn: "dictionary", example: "字引で言葉を調べます。" },
      { term: "じゃ", reading: "じゃ; じゃあ", meaningJa: "それでは、という意味", meaningEn: "well, well then", example: "じゃ、また明日。" },
      { term: "十", reading: "じゅう", meaningJa: "数字の10", meaningEn: "ten", example: "りんごを十個買います。" },
      { term: "上手", reading: "じょうず", meaningJa: "何かがよくできること", meaningEn: "be good at, skillful", example: "田中さんは料理が上手です。" },
      { term: "白", reading: "しろ", meaningJa: "雪のような色", meaningEn: "white", example: "白いシャツを着ます。" },
      { term: "吸う", reading: "すう", meaningJa: "口や鼻で空気を取り入れる", meaningEn: "to breathe in, to suck", example: "たばこを吸いません。" },
      { term: "少ない", reading: "すくない", meaningJa: "数や量が多くない", meaningEn: "a little; a few", example: "お金が少ないです。" },
      { term: "ストーブ", reading: "ストーブ", meaningJa: "部屋を暖める機械", meaningEn: "heater (lit: stove)", example: "冬はストーブを使います。" },
      { term: "する", reading: "する", meaningJa: "何かの動作を行う", meaningEn: "to do, to try; to wear small items (e.g., necktie, watch, etc.)", example: "宿題をします。" },
      { term: "石鹸", reading: "せっけん", meaningJa: "体を洗う時に使うもの", meaningEn: "soap", example: "石鹸で手を洗います。" },
      { term: "千", reading: "せん", meaningJa: "数字の1000", meaningEn: "thousand", example: "千円を払いました。" },
      { term: "全部", reading: "ぜんぶ", meaningJa: "全て、残らず全部", meaningEn: "all, entire, whole", example: "全部食べました。" },
      { term: "そちら", reading: "そちら", meaningJa: "その場所、相手のいる方", meaningEn: "over there", example: "そちらは寒いですか。" },
      { term: "そば", reading: "そば", meaningJa: "すぐ近くの場所", meaningEn: "near, close, beside; Japanese traditional buckwheat noodle", example: "駅のそばに住んでいます。" },
      { term: "～台", reading: "～だい", meaningJa: "車や機械を数える言葉", meaningEn: "counter for vehicles; machines", example: "車が二台あります。" },
      { term: "大切", reading: "たいせつ", meaningJa: "とても大事なこと", meaningEn: "important", example: "家族はとても大切です。" },
      { term: "沢山", reading: "たくさん", meaningJa: "数や量が多いこと", meaningEn: "many, much", example: "本を沢山持っています。" },
      { term: "立つ", reading: "たつ", meaningJa: "足で体を起こすこと", meaningEn: "to stand up", example: "椅子から立ちます。" },
      { term: "たばこ", reading: "たばこ", meaningJa: "吸うと煙が出るもの", meaningEn: "tobacco, cigarettes", example: "たばこは吸いません。" },
      { term: "誰", reading: "だれ", meaningJa: "人の名前を聞く言葉", meaningEn: "who", example: "あの人は誰ですか。" },
      { term: "小さな", reading: "ちいさな", meaningJa: "大きくないこと", meaningEn: "small, little", example: "小さな犬を飼っています。" },
      { term: "地下鉄", reading: "ちかてつ", meaningJa: "地下を走る電車", meaningEn: "underground train, subway", example: "地下鉄で会社へ行きます。" },
      { term: "丁度", reading: "ちょうど", meaningJa: "ぴったり、正確に", meaningEn: "just, right, exactly", example: "今、丁度三時です。" },
      { term: "着く", reading: "つく", meaningJa: "目的の場所に到着する", meaningEn: "to arrive at, to reach", example: "駅に着きました。" },
      { term: "勤める", reading: "つとめる", meaningJa: "会社などで働くこと", meaningEn: "to work (for)", example: "銀行に勤めています。" },
      { term: "テープ", reading: "テープ", meaningJa: "物を貼る細長いもの", meaningEn: "tape", example: "テープで紙を貼ります。" },
      { term: "できる", reading: "できる", meaningJa: "何かをする力がある", meaningEn: "to be able to (to accomplish)", example: "日本語が少しできます。" },
      { term: "でも", reading: "でも", meaningJa: "しかし、という意味", meaningEn: "but, however", example: "でも、時間がありません。" },
      { term: "電気", reading: "でんき", meaningJa: "明かりをつける力", meaningEn: "electricity, (electric) light", example: "電気を消してください。" },
      { term: "ドア", reading: "ドア", meaningJa: "部屋の入り口の戸", meaningEn: "door (Western style)", example: "ドアを開けてください。" },
      { term: "動物", reading: "どうぶつ", meaningJa: "生きている生き物", meaningEn: "animal", example: "動物園で動物を見ます。" },
      { term: "時計", reading: "とけい", meaningJa: "時間が分かる道具", meaningEn: "a watch; a clock", example: "時計を見てください。" },
      { term: "図書館", reading: "としょかん", meaningJa: "本を読んだり借りたりする所", meaningEn: "library", example: "図書館で本を借ります。" },
      { term: "隣", reading: "となり", meaningJa: "すぐ横の場所", meaningEn: "next to, next door to", example: "隣に座ってください。" },
      { term: "土曜日", reading: "どようび", meaningJa: "一週間の六番目の日", meaningEn: "Saturday", example: "土曜日に映画を見ます。" },
      { term: "撮る", reading: "とる", meaningJa: "写真を作ること", meaningEn: "to take (a photo), to make (a film)", example: "写真を撮ります。" },
      { term: "中", reading: "なか", meaningJa: "ものの内側", meaningEn: "inside, middle, among", example: "かばんの中に本があります。" },
      { term: "夏", reading: "なつ", meaningJa: "一番暑い季節", meaningEn: "summer", example: "夏は暑いです。" },
      { term: "七日", reading: "なのか", meaningJa: "月の七番目の日", meaningEn: "seven days; seventh day (of the month)", example: "七日に旅行に行きます。" },
      { term: "並べる", reading: "ならべる", meaningJa: "順番に置くこと", meaningEn: "to put (things) side by side; to line up", example: "机の上に本を並べます。" },
      { term: "肉", reading: "にく", meaningJa: "牛や豚などの食べ物", meaningEn: "meat", example: "肉と魚を食べます。" },
      { term: "ニュース", reading: "ニュース", meaningJa: "新しい知らせ", meaningEn: "news", example: "テレビでニュースを見ます。" },
      { term: "猫", reading: "ねこ", meaningJa: "ペットの動物", meaningEn: "cat", example: "猫が好きです。" },
      { term: "登る", reading: "のぼる", meaningJa: "山に上がること", meaningEn: "to climb", example: "山に登ります。" },
      { term: "パーティー", reading: "パーティー", meaningJa: "楽しい集まり", meaningEn: "a party", example: "友達とパーティーをします。" },
      { term: "葉書", reading: "はがき", meaningJa: "手紙を書く紙", meaningEn: "postcard", example: "友達に葉書を書きます。" },
      { term: "箸", reading: "はし", meaningJa: "食事に使う道具", meaningEn: "chopsticks", example: "箸でご飯を食べます。" },
      { term: "バス", reading: "バス", meaningJa: "大きい乗り物", meaningEn: "bus; bath; bass", example: "バスで学校へ行きます。" },
      { term: "二十日", reading: "はつか", meaningJa: "月の二十番目の日", meaningEn: "twenty days, twentieth (day of the month)", example: "二十日に国へ帰ります。" },
      { term: "母", reading: "はは", meaningJa: "自分のお母さん", meaningEn: "(my) mother", example: "母は優しいです。" },
      { term: "貼る", reading: "はる", meaningJa: "紙をつけること", meaningEn: "to post; to paste; to attach", example: "壁にポスターを貼ります。" },
      { term: "～番", reading: "～ばん", meaningJa: "順番を表す言葉", meaningEn: "~st; ~th best", example: "山田さんが一番早いです。" },
      { term: "半分", reading: "はんぶん", meaningJa: "二つに分けた一つ", meaningEn: "half", example: "りんごを半分に切ります。" },
      { term: "低い", reading: "ひくい", meaningJa: "高くないこと", meaningEn: "short, low", example: "この机は低いです。" },
      { term: "一つ", reading: "ひとつ", meaningJa: "数が1のもの", meaningEn: "one thing", example: "りんごを一つ食べます。" },
      { term: "病院", reading: "びょういん", meaningJa: "病気を治す所", meaningEn: "hospital", example: "病院で薬をもらいます。" },
      { term: "広い", reading: "ひろい", meaningJa: "とても大きいこと", meaningEn: "spacious; wide; broad", example: "この部屋は広いです。" },
      { term: "フォーク", reading: "フォーク", meaningJa: "食べ物を刺す道具", meaningEn: "fork", example: "フォークでケーキを食べます。" },
      { term: "二人", reading: "ふたり", meaningJa: "人が二人のこと", meaningEn: "two people", example: "二人で映画を見ます。" },
      { term: "古い", reading: "ふるい", meaningJa: "新しくないこと", meaningEn: "old (in reference to objects, not people), aged, ancient", example: "この本は古いです。" },
      { term: "ベッド", reading: "ベッド", meaningJa: "寝るための家具", meaningEn: "bed", example: "ベッドで寝ます。" },
      { term: "ペン", reading: "ペン", meaningJa: "字を書く道具", meaningEn: "pen", example: "ペンで名前を書きます。" },
      { term: "ポケット", reading: "ポケット", meaningJa: "服の小さい袋", meaningEn: "pocket", example: "ポケットにお金を入れます。" },
      { term: "ホテル", reading: "ホテル", meaningJa: "泊まるところ", meaningEn: "hotel", example: "ホテルに泊まります。" },
      { term: "～枚", reading: "～まい", meaningJa: "薄い物を数える言葉", meaningEn: "counter for flat things", example: "紙を三枚ください。" },
      { term: "曲る", reading: "まがる", meaningJa: "方向を変えること", meaningEn: "to turn, to bend", example: "次の角を右に曲がります。" },
      { term: "待つ", reading: "まつ", meaningJa: "来るまでそこにいる", meaningEn: "to wait", example: "友達を待ちます。" },
      { term: "丸い", reading: "まるい", meaningJa: "円の形のこと", meaningEn: "round, circular", example: "地球は丸いです。" },
      { term: "短い", reading: "みじかい", meaningJa: "長くないこと", meaningEn: "short (length)", example: "この鉛筆は短いです。" },
      { term: "三日", reading: "みっか", meaningJa: "月の三番目の日", meaningEn: "three days, third day of the month", example: "三日に旅行します。" },
      { term: "耳", reading: "みみ", meaningJa: "音を聞く体の部分", meaningEn: "ear", example: "耳で音楽を聞きます。" },
      { term: "向こう", reading: "むこう", meaningJa: "あちらの場所", meaningEn: "beyond, over there", example: "向こうに山が見えます。" },
      { term: "メートル", reading: "メートル", meaningJa: "長さの単位", meaningEn: "meter", example: "この道は百メートルです。" },
      { term: "持つ", reading: "もつ", meaningJa: "手にとること", meaningEn: "to hold, to carry; to possess", example: "かばんを持ちます。" },
      { term: "～屋", reading: "～や", meaningJa: "物を売る店", meaningEn: "~ shop", example: "パン屋でパンを買います。" },
      { term: "安い", reading: "やすい", meaningJa: "値段が低いこと", meaningEn: "inexpensive; cheap (things)", example: "この店は安いです。" },
      { term: "やる", reading: "やる", meaningJa: "何かをすること", meaningEn: "to do; to give (to pets, parents, siblings, etc.)", example: "宿題をやります。" },
      { term: "有名", reading: "ゆうめい", meaningJa: "みんなが知っている", meaningEn: "famous", example: "この歌手は有名です。" },
      { term: "洋服", reading: "ようふく", meaningJa: "西洋風の服", meaningEn: "Western-style clothes", example: "新しい洋服を買います。" },
      { term: "呼ぶ", reading: "よぶ", meaningJa: "声をかけること", meaningEn: "to call (one's name); to invite", example: "友達をパーティーに呼びます。" },
      { term: "来週", reading: "らいしゅう", meaningJa: "今週の次の週", meaningEn: "next week", example: "来週日本へ行きます。" },
      { term: "留学生", reading: "りゅうがくせい", meaningJa: "外国で勉強する学生", meaningEn: "international student", example: "彼はアメリカの留学生です。" },
      { term: "零", reading: "れい", meaningJa: "数字のゼロ", meaningEn: "zero, nought", example: "点数は零でした。" },
      { term: "廊下", reading: "ろうか", meaningJa: "建物の中の道", meaningEn: "corridor", example: "廊下を走らないでください。" },
      { term: "忘れる", reading: "わすれる", meaningJa: "覚えていないこと", meaningEn: "to forget", example: "宿題を忘れました。" },
    ],
    grammar: [
      { pattern: "〜ています", meaningEn: "ongoing action / current state", example: "今、勉強しています。" },
      { pattern: "〜たいです", meaningEn: "want to do", example: "日本へ行きたいです。" },
      { pattern: "〜ないでください", meaningEn: "please don't do", example: "ここで写真を撮らないでください。" },
      { pattern: "〜前に", meaningEn: "before doing", example: "寝る前に歯を磨きます。" },
      { pattern: "〜ことができます", meaningEn: "can do", example: "私は漢字を読むことができます。" },
      // --- Expanded N5 grammar (round 1) ---
      { pattern: "は", meaningEn: "topic marker (as for ~)", example: "わたしは学生です。" },
      { pattern: "が", meaningEn: "subject marker", example: "猫がいます。" },
      { pattern: "を", meaningEn: "direct object marker", example: "パンを食べます。" },
      { pattern: "に（時間・場所）", meaningEn: "at / on / to (time, destination, indirect object)", example: "七時に起きます。" },
      { pattern: "で", meaningEn: "at / by (location of an action, means)", example: "図書館で勉強します。" },
      { pattern: "へ", meaningEn: "toward (direction)", example: "学校へ行きます。" },
      { pattern: "と", meaningEn: "with / and (exhaustive listing)", example: "友達と映画を見ます。" },
      { pattern: "も", meaningEn: "also / too", example: "わたしも行きます。" },
      { pattern: "の", meaningEn: "possessive particle / nominalizer", example: "これはわたしの本です。" },
      { pattern: "〜から〜まで", meaningEn: "from ~ to ~", example: "九時から五時まで働きます。" },
      { pattern: "や", meaningEn: "and (non-exhaustive listing)", example: "机の上に本やペンがあります。" },
      { pattern: "か", meaningEn: "question marker / or", example: "これは辞書ですか。" },
      { pattern: "ね", meaningEn: "seeking agreement / confirmation", example: "今日は暑いですね。" },
      { pattern: "よ", meaningEn: "informing / emphasis", example: "もうすぐ電車が来ますよ。" },
      { pattern: "〜ます／〜ません", meaningEn: "polite present affirmative / negative", example: "毎朝コーヒーを飲みます。お酒は飲みません。" },
      { pattern: "〜ました／〜ませんでした", meaningEn: "polite past affirmative / negative", example: "昨日は雨が降りました。" },
      { pattern: "〜てもいいです", meaningEn: "may / is allowed to (permission)", example: "ここに座ってもいいです。" },
      { pattern: "〜てはいけません", meaningEn: "must not (prohibition)", example: "ここでたばこを吸ってはいけません。" },
      { pattern: "〜た後で", meaningEn: "after doing", example: "宿題をした後で、テレビを見ます。" },
      { pattern: "〜ながら", meaningEn: "while doing (two actions at once)", example: "音楽を聞きながら勉強します。" },
      { pattern: "〜とき", meaningEn: "when / at the time of", example: "日本へ来たとき、日本語が話せませんでした。" },
      { pattern: "〜たり〜たりします", meaningEn: "do things like ~ and ~", example: "週末は本を読んだり、映画を見たりします。" },
      { pattern: "〜なければなりません", meaningEn: "must do / have to", example: "宿題を今日中にしなければなりません。" },
      { pattern: "〜でしょう", meaningEn: "probably (conjecture)", example: "明日は晴れるでしょう。" },
      { pattern: "〜すぎます", meaningEn: "too much (excessive)", example: "これは食べすぎました。" },
    ],
    questions: [
      { category: "vocabulary", prompt: "「食べる」の意味はどれですか。", choices: ["to eat", "to drink", "to sleep", "to run"], correctIndex: 0, explanation: "「食べる」= to eat。" },
      { category: "vocabulary", prompt: "「忙しい」の意味はどれですか。", choices: ["quiet", "busy", "beautiful", "boring"], correctIndex: 1, explanation: "「忙しい」= busy。" },
      { category: "vocabulary", prompt: "「でんしゃ」を漢字で書くとどれですか。", choices: ["電車", "電話", "自転車", "飛行機"], correctIndex: 0, explanation: "でんしゃ = 電車 (train)。" },
      { category: "grammar", prompt: "「毎日日本語を＿＿。」空欄に入るのはどれですか。", choices: ["勉強します", "勉強たいです", "勉強ています", "勉強前に"], correctIndex: 0, explanation: "習慣を表す現在形「勉強します」が自然です。" },
      { category: "grammar", prompt: "「ここで写真を＿＿ください。」空欄に入るのはどれですか。", choices: ["撮って", "撮らないで", "撮る", "撮りたい"], correctIndex: 1, explanation: "禁止のお願いは「〜ないでください」。" },
      { category: "grammar", prompt: "「寝る＿＿歯を磨きます。」空欄に入るのはどれですか。", choices: ["前に", "後で", "ながら", "とき、"], correctIndex: 0, explanation: "「〜前に」= before doing。" },
      { category: "listening", prompt: "（会話）A「明日、何をしますか。」B「友達と映画を見ます。」\n質問：Bさんは明日何をしますか。", choices: ["勉強します", "映画を見ます", "電車に乗ります", "水を飲みます"], correctIndex: 1, explanation: "Bは「映画を見ます」と答えています。" },
      { category: "listening", prompt: "（会話）A「学校まで何で行きますか。」B「電車で行きます。」\n質問：学校までの交通手段はどれですか。", choices: ["バス", "電車", "自転車", "徒歩"], correctIndex: 1, explanation: "「電車で行きます」と言っています。" },
      { category: "listening", prompt: "（会話）A「今日は忙しいですか。」B「いいえ、あまり忙しくないです。」\n質問：Bさんは今日忙しいですか。", choices: ["とても忙しい", "あまり忙しくない", "わからない", "少し忙しい"], correctIndex: 1, explanation: "「あまり忙しくない」= not very busy。" },
      { category: "reading", prompt: "（文章）わたしは毎日六時に起きます。朝ごはんを食べてから、電車で学校へ行きます。\n質問：「わたし」はいつ起きますか。", choices: ["五時", "六時", "七時", "八時"], correctIndex: 1, explanation: "「毎日六時に起きます」とあります。" },
      { category: "reading", prompt: "（文章）土曜日、友達と大きい公園へ行きました。天気がよかったです。\n質問：どこへ行きましたか。", choices: ["学校", "公園", "駅", "図書館"], correctIndex: 1, explanation: "「大きい公園へ行きました」とあります。" },
      { category: "reading", prompt: "（文章）田中さんは水を三本買いました。\n質問：田中さんは何を買いましたか。", choices: ["パン", "水", "電車の切符", "本"], correctIndex: 1, explanation: "「水を三本買いました」とあります。" },
    ],
  },
  N4: {
    vocab: [
      { term: "経験", reading: "けいけん", meaningJa: "実際にやったこと", meaningEn: "experience", example: "海外で働いた経験があります。" },
      { term: "準備", reading: "じゅんび", meaningJa: "前もって用意すること", meaningEn: "preparation", example: "旅行の準備をします。" },
      { term: "説明", reading: "せつめい", meaningJa: "わかるように話すこと", meaningEn: "explanation", example: "先生が文法を説明します。" },
      { term: "世界", reading: "せかい", meaningJa: "全ての国", meaningEn: "world", example: "世界には多くの国があります。" },
      { term: "台風", reading: "たいふう", meaningJa: "強い風の嵐", meaningEn: "typhoon", example: "台風が近づいています。" },
      { term: "用意", reading: "ようい", meaningJa: "準備すること", meaningEn: "readiness", example: "夕食の用意をしています。" },
      { term: "天気予報", reading: "てんきよほう", meaningJa: "天気の予測", meaningEn: "weather forecast", example: "天気予報を見ます。" },
      { term: "招待", reading: "しょうたい", meaningJa: "呼ぶこと", meaningEn: "invitation", example: "パーティーに招待されました。" },
      // --- Expanded N4 vocabulary (round 2 of the content-volume expansion) ---
      // Sourced from elzup/jlpt-word-list (MIT license), same approach as N5.
      { term: "踏む", reading: "ふむ", meaningJa: "上から足を乗せること", meaningEn: "to step on, to tread on", example: "電車の中で人の足を踏んでしまった。" },
      { term: "大抵", reading: "たいてい", meaningJa: "ほとんどの場合", meaningEn: "generally, usually", example: "休みの日は大抵家で本を読みます。" },
      { term: "しっかり", reading: "しっかり", meaningJa: "強くてじょうぶな様子", meaningEn: "firmly, steady", example: "彼はしっかりした考えを持っている。" },
      { term: "やはり", reading: "やはり", meaningJa: "思っていた通り", meaningEn: "as I thought, absolutely", example: "やはり彼女は来なかった。" },
      { term: "テキスト", reading: "テキスト", meaningJa: "勉強に使う本", meaningEn: "text; text book", example: "このテキストを使って文法を勉強します。" },
      { term: "聞こえる", reading: "きこえる", meaningJa: "音が耳に入ること", meaningEn: "to be heard, to be audible", example: "隣の部屋から音楽が聞こえる。" },
      { term: "怒る", reading: "おこる", meaningJa: "腹を立てること", meaningEn: "to get angry; to scold angrily", example: "遅刻して先生に怒られた。" },
      { term: "もし", reading: "もし", meaningJa: "仮定を表す言葉", meaningEn: "if", example: "もし雨が降ったら、試合は中止です。" },
      { term: "予習", reading: "よしゅう", meaningJa: "授業の前に勉強すること", meaningEn: "preparation of lessons (for class)", example: "明日の授業のために予習をしておく。" },
      { term: "お宅", reading: "おたく", meaningJa: "相手の家を丁寧に言う言葉", meaningEn: "(someone else's) house; home -- polite word for 家 (いえ) --", example: "明日、お宅に伺ってもよろしいですか。" },
      { term: "比べる", reading: "くらべる", meaningJa: "違いを見比べること", meaningEn: "to compare", example: "去年と今年の気温を比べてみた。" },
      { term: "だめ", reading: "だめ", meaningJa: "よくないこと", meaningEn: "useless, no good, hopeless", example: "ここでたばこを吸ってはだめです。" },
      { term: "発音", reading: "はつおん", meaningJa: "言葉の音の出し方", meaningEn: "pronunciation", example: "先生の発音を聞いて真似をする。" },
      { term: "ごみ", reading: "ごみ", meaningJa: "いらなくなった物", meaningEn: "trash, garbage", example: "ごみは月曜日に出してください。" },
      { term: "機会", reading: "きかい", meaningJa: "何かをするいい時", meaningEn: "chance, opportunity", example: "日本人と話す機会が増えました。" },
      { term: "いらっしゃる", reading: "いらっしゃる", meaningJa: "行く・来る・いるの尊敬語", meaningEn: "-- honorific expression for いく, くる, and いる --", example: "社長は今、会議室にいらっしゃいます。" },
      { term: "～製", reading: "～せい", meaningJa: "そこで作られたこと", meaningEn: "made in ~", example: "これは日本製のカメラです。" },
      { term: "～軒", reading: "～けん", meaningJa: "家を数える言葉", meaningEn: "counter for houses", example: "この道には店が三軒あります。" },
      { term: "レポート", reading: "レポート", meaningJa: "調べたことをまとめた文書", meaningEn: "report", example: "来週までにレポートを提出してください。" },
      { term: "すると", reading: "すると", meaningJa: "そうしたら", meaningEn: "and, then", example: "ボタンを押した。すると、ドアが開いた。" },
      { term: "厳しい", reading: "きびしい", meaningJa: "とても厳格な様子", meaningEn: "hard; rigorous; strict", example: "あの先生はとても厳しいです。" },
      { term: "ちっとも", reading: "ちっとも", meaningJa: "全く～ない様子", meaningEn: "not at all (neg. verb)", example: "この本はちっとも面白くない。" },
      { term: "落る", reading: "おちる", meaningJa: "上から下に動くこと", meaningEn: "to fall, to drop", example: "りんごが木から落ちる。" },
      { term: "祈る", reading: "いのる", meaningJa: "神様にお願いすること", meaningEn: "to pray; to wish", example: "家族の健康を祈っています。" },
      { term: "致す", reading: "いたす", meaningJa: "するの謙譲語", meaningEn: "-- extra-modest expression for する --", example: "私がご案内致します。" },
      { term: "うそ", reading: "嘘", meaningJa: "本当ではないこと", meaningEn: "lie", example: "彼はすぐうそをつく。" },
      { term: "思う", reading: "おもう", meaningJa: "心の中でそう考えること", meaningEn: "to think, to feel", example: "明日は晴れると思います。" },
      { term: "～式", reading: "～しき", meaningJa: "儀式、または方法", meaningEn: "~ ceremony; ~ style", example: "来月、卒業式があります。" },
      { term: "建て", reading: "～だて", meaningJa: "家の階数を表す言葉", meaningEn: "~ storied, separate housing", example: "彼は二階建ての家に住んでいます。" },
      { term: "季節", reading: "きせつ", meaningJa: "春・夏・秋・冬のこと", meaningEn: "season (in reference to weather)", example: "日本には四つの季節があります。" },
      { term: "だから", reading: "だから", meaningJa: "その理由で", meaningEn: "so; therefore", example: "雨が降っている。だから傘を持って行く。" },
      { term: "地理", reading: "ちり", meaningJa: "土地の様子を研究する学問", meaningEn: "geography", example: "大学で日本の地理を勉強しています。" },
      { term: "無理", reading: "むり", meaningJa: "できないこと", meaningEn: "unreasonable, impossible", example: "今日中に終わらせるのは無理です。" },
      { term: "人形", reading: "にんぎょう", meaningJa: "人の形をしたおもちゃ", meaningEn: "doll, figure", example: "娘に人形をプレゼントした。" },
      { term: "いくら～ても", reading: "いくら～ても", meaningJa: "どんなに～しても", meaningEn: "however much one may ~", example: "いくら頑張っても、うまくいかない。" },
      { term: "投げる", reading: "なげる", meaningJa: "物を手で遠くへ飛ばすこと", meaningEn: "to pitch, to cast away", example: "子供にボールを投げてあげた。" },
      { term: "気分", reading: "きぶん", meaningJa: "その時の心や体の様子", meaningEn: "feeling, mood", example: "今日は気分が悪いので休みます。" },
      { term: "やっと", reading: "やっと", meaningJa: "長い時間の後にようやく", meaningEn: "at last, finally", example: "やっと仕事が終わった。" },
      { term: "無くなる", reading: "なくなる", meaningJa: "なくなってしまうこと", meaningEn: "to disappear, to get lost", example: "財布がどこかで無くなってしまった。" },
      { term: "林", reading: "はやし", meaningJa: "木がたくさんある所", meaningEn: "woods, forest", example: "家の後ろに小さな林があります。" },
      { term: "戦争", reading: "せんそう", meaningJa: "国と国が武力で争うこと", meaningEn: "war", example: "祖父は戦争について話してくれた。" },
      { term: "光る", reading: "ひかる", meaningJa: "光を出すこと", meaningEn: "to shine, to glitter", example: "夜空に星が光っている。" },
      { term: "事務所", reading: "じむしょ", meaningJa: "仕事をする建物や部屋", meaningEn: "office", example: "父は毎日事務所で働いています。" },
      { term: "美しい", reading: "うつくしい", meaningJa: "とてもきれいな様子", meaningEn: "beautiful, lovely", example: "山の上から美しい景色が見えた。" },
      { term: "どんどん", reading: "どんどん", meaningJa: "勢いよく続く様子", meaningEn: "quickly and steadily; at a rapid pace", example: "日本語がどんどん上手になっている。" },
      { term: "文法", reading: "ぶんぽう", meaningJa: "言葉の正しい使い方の規則", meaningEn: "grammar", example: "日本語の文法は難しいです。" },
      { term: "お礼", reading: "おれい", meaningJa: "感謝の気持ちを表すこと", meaningEn: "expression of gratitude; thanking; gift of appreciation; bow", example: "お世話になった先生にお礼を言った。" },
      { term: "始める", reading: "はじめる", meaningJa: "物事を新しく開始すること", meaningEn: "to start, to begin", example: "来月から新しい仕事を始めます。" },
      { term: "熱", reading: "ねつ", meaningJa: "体温が高くなること", meaningEn: "fever, temperature", example: "熱があるので今日は休みます。" },
      { term: "ベル", reading: "ベル", meaningJa: "音を鳴らす道具", meaningEn: "bell", example: "ベルが鳴ったら教室に入ってください。" },
      { term: "辞典", reading: "じてん", meaningJa: "言葉の意味を調べる本", meaningEn: "encyclopedia, reference book", example: "分からない言葉があったら、辞典で調べてください。" },
      { term: "～員", reading: "～いん", meaningJa: "その仕事をしている人", meaningEn: "member of ~", example: "兄は銀行員として働いています。" },
      { term: "場所", reading: "ばしょ", meaningJa: "物や人がある所", meaningEn: "place, location", example: "待ち合わせの場所を決めましょう。" },
      { term: "受付", reading: "うけつけ", meaningJa: "来た人に応対する所", meaningEn: "reception(ist) desk", example: "受付で名前を書いてください。" },
      { term: "けがする", reading: "けがする", meaningJa: "体を傷つけること", meaningEn: "injury (to animate object), hurt", example: "自転車で転んで、足をけがしました。" },
      { term: "心", reading: "こころ", meaningJa: "気持ちや考えるところ", meaningEn: "heart, mind", example: "彼女はいつも心が温かいです。" },
      { term: "景色", reading: "けしき", meaningJa: "山や海などの眺め", meaningEn: "scenery, landscape", example: "山の上から見る景色はきれいでした。" },
      { term: "森", reading: "もり", meaningJa: "木がたくさんある所", meaningEn: "forest", example: "森の中を散歩するのが好きです。" },
      { term: "乾く", reading: "かわく", meaningJa: "水分がなくなること", meaningEn: "to get dry", example: "洗濯物がよく乾きました。" },
      { term: "塗る", reading: "ぬる", meaningJa: "色や薬などをつけること", meaningEn: "to paint, to plaster", example: "壁に白いペンキを塗りました。" },
      { term: "公務員", reading: "こうむいん", meaningJa: "国や市で働く人", meaningEn: "government worker, public servant", example: "姉は市役所で働く公務員です。" },
      { term: "運転", reading: "うんてんする", meaningJa: "車などを動かすこと", meaningEn: "driving", example: "父は毎日車を運転して会社に行きます。" },
      { term: "消しゴム", reading: "けしゴム", meaningJa: "字を消す道具", meaningEn: "eraser", example: "間違えたので、消しゴムで消しました。" },
      { term: "育てる", reading: "そだてる", meaningJa: "大きくなるように世話すること", meaningEn: "to raise (v.t.); to bring up", example: "庭で野菜を育てています。" },
      { term: "案内", reading: "あんないする", meaningJa: "道や場所を教えること", meaningEn: "information, guidance", example: "駅まで道を案内してもらいました。" },
      { term: "下宿", reading: "げしゅく", meaningJa: "お金を払って住む家", meaningEn: "lodging, boarding house", example: "大学の近くの下宿に住んでいます。" },
      { term: "はず", reading: "はず", meaningJa: "きっとそうだという意味", meaningEn: "it should be so", example: "彼はもう家に着いているはずです。" },
      { term: "貿易", reading: "ぼうえき", meaningJa: "外国と物を売り買いすること", meaningEn: "trade", example: "この会社は貿易の仕事をしています。" },
      { term: "真面目", reading: "まじめ", meaningJa: "熱心でうそをつかない様子", meaningEn: "diligent, serious", example: "彼はいつも真面目に勉強しています。" },
      { term: "よろしい", reading: "よろしい", meaningJa: "「いい」の丁寧な言い方", meaningEn: "(hon.) good, OK, all right", example: "こちらの席でよろしいですか。" },
      { term: "空気", reading: "くうき", meaningJa: "私たちが吸っている気体", meaningEn: "air, atmosphere", example: "山の空気はとてもきれいです。" },
      { term: "急行", reading: "きゅうこう", meaningJa: "早く着く電車やバス", meaningEn: "express train or bus", example: "急行に乗れば、もっと早く着きます。" },
      { term: "校長", reading: "こうちょう", meaningJa: "学校で一番上の先生", meaningEn: "principal, headmaster", example: "校長先生が朝の会であいさつしました。" },
      { term: "引っ越す", reading: "ひっこす", meaningJa: "住む家を変えること", meaningEn: "to move to a new place of residence", example: "来月、新しいアパートに引っ越します。" },
      { term: "亡くなる", reading: "なくなる", meaningJa: "死ぬことの丁寧な言い方", meaningEn: "to pass away", example: "祖父は去年、病気で亡くなりました。" },
      { term: "祖父", reading: "そふ", meaningJa: "父か母の父親", meaningEn: "grandfather", example: "祖父は毎朝、公園を散歩しています。" },
      { term: "入学", reading: "にゅうがくする", meaningJa: "学校に入ること", meaningEn: "entry to school or university", example: "来年、大学に入学する予定です。" },
      { term: "火事", reading: "かじ", meaningJa: "建物などが燃えること", meaningEn: "fire", example: "昨日の夜、近くで火事がありました。" },
      { term: "いっぱい", reading: "一杯", meaningJa: "たくさんあって満ちている様子", meaningEn: "full, to the utmost", example: "お腹がいっぱいで、もう食べられません。" },
      { term: "着物", reading: "きもの", meaningJa: "日本の伝統的な服", meaningEn: "kimono; Japanese traditional dress", example: "お祭りで着物を着る人が多かったです。" },
      { term: "～ちゃん", reading: "～ちゃん", meaningJa: "親しい人の名前につける言葉", meaningEn: "suffix for familiar (female) person", example: "花ちゃんは今年五歳になりました。" },
      { term: "教育", reading: "きょういく", meaningJa: "知識や考え方を教えること", meaningEn: "education", example: "子どもの教育について夫婦で話し合いました。" },
      { term: "国際", reading: "こくさい", meaningJa: "いろいろな国に関係すること", meaningEn: "international", example: "この町では国際交流のイベントがあります。" },
      { term: "夢", reading: "ゆめ", meaningJa: "寝ている時に見るものや将来の望み", meaningEn: "a dream", example: "将来、医者になるのが私の夢です。" },
      { term: "不便", reading: "ふべん", meaningJa: "便利ではなく困ること", meaningEn: "inconvenience", example: "この辺りは店が少なくて不便です。" },
      { term: "ひどい", reading: "ひどい", meaningJa: "とても悪い、程度が激しい様子", meaningEn: "terrible, awful, unfair, cruel", example: "昨日の台風はひどい風でした。" },
      { term: "押し入れ", reading: "おしいれ", meaningJa: "布団などをしまう場所", meaningEn: "closet", example: "布団を押し入れにしまいました。" },
      { term: "びっくりする", reading: "びっくりする", meaningJa: "急に驚くこと", meaningEn: "to be surprised", example: "大きな音がして、びっくりしました。" },
      { term: "沸かす", reading: "わかす", meaningJa: "水などを熱くすること", meaningEn: "to boil", example: "お湯を沸かしてお茶を入れました。" },
      { term: "空く", reading: "あく", meaningJa: "中が空になること", meaningEn: "to open, to become empty (vacant)", example: "隣の席が空いたので座りました。" },
      { term: "こう", reading: "こう", meaningJa: "このように、という意味", meaningEn: "like this, this way", example: "この漢字はこう書きます。" },
      { term: "おいでになる", reading: "おいでになる", meaningJa: "「いる」「来る」の尊敬語", meaningEn: "(hon.) to be", example: "先生は今、教室においでになります。" },
      { term: "ハンバーグ", reading: "ハンバーグ", meaningJa: "ひき肉を焼いた料理", meaningEn: "hamburger steak", example: "夕食にハンバーグを作りました。" },
      { term: "～始める", reading: "～はじめる", meaningJa: "することを始めるという意味", meaningEn: "to start doing ~", example: "六時ごろから雨が降り始めました。" },
      { term: "きっと", reading: "きっと", meaningJa: "たぶん確かにそうだという意味", meaningEn: "surely, definitely, undoubtedly, certainly", example: "彼はきっと約束を守るでしょう。" },
      { term: "正しい", reading: "ただしい", meaningJa: "間違っていない様子", meaningEn: "correct", example: "正しい答えを選んでください。" },
      { term: "産業", reading: "さんぎょう", meaningJa: "物を作って売る仕事全体", meaningEn: "industry", example: "この地域は自動車産業が盛んです。" },
      { term: "道具", reading: "どうぐ", meaningJa: "何かをする時に使う物", meaningEn: "tool", example: "料理の道具をきれいに洗いました。" },
      { term: "～まま", reading: "～まま", meaningJa: "状態が変わらないこと", meaningEn: "as it is", example: "靴を履いたまま部屋に入らないでください。" },
      { term: "妻", reading: "つま", meaningJa: "自分の結婚相手の女性", meaningEn: "wife (humble)", example: "妻は料理が上手です。" },
      { term: "スーツ", reading: "スーツ", meaningJa: "仕事などで着る服", meaningEn: "suit", example: "明日の面接にはスーツを着ていきます。" },
      { term: "彼女", reading: "かのじょ", meaningJa: "恋人の女性", meaningEn: "girlfriend; she", example: "彼女と映画を見に行きました。" },
      { term: "専門", reading: "せんもん", meaningJa: "特に詳しく学ぶこと", meaningEn: "major; speciality", example: "大学で経済学を専門に勉強しています。" },
      { term: "騒ぐ", reading: "さわぐ", meaningJa: "うるさい音を出すこと", meaningEn: "to make noise, to clamor", example: "子供たちが公園で騒いでいます。" },
      { term: "ファックス", reading: "ファックス", meaningJa: "書類を送る機械", meaningEn: "fax", example: "この書類をファックスで送ってください。" },
      { term: "見つける", reading: "みつける", meaningJa: "探して手に入れること", meaningEn: "to discover, to find (v.t.)", example: "公園で鍵を見つけました。" },
      { term: "忘れ物", reading: "わすれもの", meaningJa: "うっかり忘れた物", meaningEn: "lost article, something forgotten", example: "電車の中に忘れ物をしてしまいました。" },
      { term: "承知", reading: "しょうちする", meaningJa: "分かって認めること", meaningEn: "consent, acceptance", example: "その条件で承知しました。" },
      { term: "～おわる", reading: "～おわる", meaningJa: "することが終わること", meaningEn: "to finish doing ~", example: "宿題を書き終わりました。" },
      { term: "慣れる", reading: "なれる", meaningJa: "習慣になって平気になること", meaningEn: "to grow accustomed to", example: "新しい仕事にだいぶ慣れました。" },
      { term: "くださる", reading: "くださる", meaningJa: "「くれる」の丁寧な言い方", meaningEn: "(hon.) to give, to confer", example: "先生が本をくださいました。" },
      { term: "運ぶ", reading: "はこぶ", meaningJa: "物を持って移動させること", meaningEn: "to transport, to carry", example: "荷物を車で運びます。" },
      { term: "席", reading: "せき", meaningJa: "座る場所", meaningEn: "a seat", example: "この席は空いていますか。" },
      { term: "アジア", reading: "アジア", meaningJa: "日本などがある地域", meaningEn: "Asia", example: "アジアにはたくさんの国があります。" },
      { term: "合う", reading: "あう", meaningJa: "ぴったり同じになること", meaningEn: "to fit, to match", example: "このズボンは私に合いません。" },
      { term: "展覧会", reading: "てんらんかい", meaningJa: "作品を見せるための会", meaningEn: "exhibition", example: "週末に絵の展覧会に行きます。" },
      { term: "遅れる", reading: "おくれる", meaningJa: "時間に間に合わないこと", meaningEn: "to (be) become late", example: "電車が遅れて会社に遅刻しました。" },
      { term: "注射", reading: "ちゅうしゃ", meaningJa: "針で薬を体に入れること", meaningEn: "injection", example: "病院でインフルエンザの注射をしました。" },
      { term: "安心", reading: "あんしん", meaningJa: "心配がなくて安らかなこと", meaningEn: "peace of mind, relief", example: "子供が無事に着いて安心しました。" },
      { term: "続く", reading: "つづく", meaningJa: "同じ状態が終わらずに進むこと", meaningEn: "to be continued", example: "雨がもう三日も続いています。" },
      { term: "将来", reading: "しょうらい", meaningJa: "これから先の時間", meaningEn: "(in the) future; prospects", example: "将来は医者になりたいです。" },
      { term: "払う", reading: "はらう", meaningJa: "お金を渡すこと", meaningEn: "to pay", example: "レジでお金を払います。" },
      { term: "点く", reading: "つく", meaningJa: "明かりがともること", meaningEn: "to be started, to be switched on", example: "部屋の電気が点きました。" },
      { term: "続ける", reading: "つづける", meaningJa: "やめないで行うこと", meaningEn: "to continue, to keep up", example: "毎日日本語の勉強を続けています。" },
      { term: "割れる", reading: "われる", meaningJa: "物が壊れて分かれること", meaningEn: "to break", example: "コップが落ちて割れました。" },
      { term: "回る、回す", reading: "まわる、まわす", meaningJa: "ぐるぐる動くこと", meaningEn: "to go around, to revolve", example: "地球は太陽の周りを回っています。" },
      { term: "濡れる", reading: "ぬれる", meaningJa: "水などで湿ること", meaningEn: "to get wet", example: "雨で服が濡れてしまいました。" },
      { term: "向かう", reading: "むかう", meaningJa: "その方向へ進むこと", meaningEn: "to face, to go towards", example: "これから駅に向かいます。" },
      { term: "程", reading: "ほど", meaningJa: "だいたいの程度や量", meaningEn: "degree, extent", example: "十分ほど待ってください。" },
      { term: "スーツケース", reading: "スーツケース", meaningJa: "旅行用の大きなかばん", meaningEn: "suitcase", example: "スーツケースに荷物を詰めました。" },
      { term: "紹介", reading: "しょうかい", meaningJa: "人や物を知らせること", meaningEn: "an introduction", example: "友達に彼氏を紹介しました。" },
      { term: "コンサート", reading: "コンサート", meaningJa: "音楽を聞く会", meaningEn: "concert", example: "好きな歌手のコンサートに行きました。" },
      { term: "植える", reading: "うえる", meaningJa: "土に木や花を入れて育てること", meaningEn: "to plant", example: "庭に花を植えました。" },
      { term: "急ぐ", reading: "いそぐ", meaningJa: "早くしようとすること", meaningEn: "to hurry, to be in a hurry, to rush", example: "遅刻しそうなので急いでいます。" },
      { term: "特別", reading: "とくべつ", meaningJa: "普通とは違うこと", meaningEn: "special", example: "今日は特別な日なので外食します。" },
      { term: "真中", reading: "まんなか", meaningJa: "ちょうど中央の場所", meaningEn: "middle, center", example: "机の真中に花を置きました。" },
      { term: "草", reading: "くさ", meaningJa: "地面に生える緑の植物", meaningEn: "grass", example: "公園に草がたくさん生えています。" },
      { term: "花見", reading: "はなみ", meaningJa: "桜の花を見て楽しむこと", meaningEn: "cherry-blossom viewing", example: "春に友達と花見をしました。" },
      { term: "別れる", reading: "わかれる", meaningJa: "一緒にいた人と離れること", meaningEn: "to part from, to separate", example: "駅で友達と別れました。" },
      { term: "相談", reading: "そうだんする", meaningJa: "人に話して意見を聞くこと", meaningEn: "consultation", example: "進路について先生に相談しました。" },
      { term: "上がる", reading: "あがる", meaningJa: "低い所から高くなること", meaningEn: "to rise, to go up", example: "気温がだんだん上がっています。" },
      { term: "娘", reading: "むすめ", meaningJa: "自分の子供の女の子", meaningEn: "daughter (humble)", example: "娘は今年小学生になりました。" },
      { term: "集まる", reading: "あつまる", meaningJa: "人や物が一か所に来ること", meaningEn: "to gather (v.i.), to collect", example: "公園に大勢の人が集まりました。" },
      { term: "関係", reading: "かんけい", meaningJa: "物事のつながり", meaningEn: "relation(ship), connection", example: "この二つの事件には関係があります。" },
      { term: "棚", reading: "たな", meaningJa: "物を置くための台", meaningEn: "shelves, rack", example: "本を棚に並べました。" },
      { term: "すり", reading: "すり", meaningJa: "人の物を盗む人", meaningEn: "pickpocket", example: "電車の中ですりに財布を取られました。" },
      { term: "大分", reading: "だいぶ", meaningJa: "かなり、相当に", meaningEn: "fairly well, to a large extent, considerably, pretty much", example: "病気は大分よくなりました。" },
      { term: "家内", reading: "かない", meaningJa: "自分の妻を指す言葉", meaningEn: "(one's own) wife", example: "家内と買い物に行きました。" },
    ],
    grammar: [
      { pattern: "〜そうです", meaningEn: "looks like / seems", example: "雨が降りそうです。" },
      { pattern: "〜ようになる", meaningEn: "come to be able to", example: "漢字が読めるようになりました。" },
      { pattern: "〜たら", meaningEn: "if / when", example: "時間があったら、電話してください。" },
      { pattern: "〜のに", meaningEn: "although / even though", example: "頑張ったのに、失敗しました。" },
      { pattern: "〜ばかり", meaningEn: "only / just", example: "彼はゲームばかりしています。" },
      // --- Expanded N4 grammar (round 2) ---
      { pattern: "〜てしまう", meaningEn: "to finish completely / to do something regrettable", example: "宿題を全部やってしまいました。" },
      { pattern: "〜てみる", meaningEn: "to try doing", example: "この料理を食べてみます。" },
      { pattern: "〜ておく", meaningEn: "to do in advance / to leave (a state) as is", example: "旅行の前に切符を買っておきます。" },
      { pattern: "〜てあげる", meaningEn: "to do (a favor) for someone", example: "友達に本を貸してあげました。" },
      { pattern: "〜てくれる", meaningEn: "someone does (a favor) for me", example: "友達が手伝ってくれました。" },
      { pattern: "〜てもらう", meaningEn: "to receive the favor of someone doing something", example: "先生に日本語を教えてもらいました。" },
      { pattern: "〜なさい", meaningEn: "polite/parental command (do ~)", example: "早く寝なさい。" },
      { pattern: "〜そうだ（伝聞）", meaningEn: "I heard that ~ (hearsay)", example: "天気予報によると、明日は雨だそうです。" },
      { pattern: "〜という", meaningEn: "called ~ / that is said to be ~", example: "田中さんという人から電話がありました。" },
      { pattern: "〜はずだ", meaningEn: "should be / is expected to be", example: "彼はもう着いているはずです。" },
      { pattern: "〜かもしれない", meaningEn: "might, may (possibility)", example: "明日は雪が降るかもしれません。" },
      { pattern: "〜だろう", meaningEn: "probably (plain form, less formal than でしょう)", example: "彼はもうすぐ来るだろう。" },
      { pattern: "〜ようだ", meaningEn: "seems like, appears (based on observation)", example: "誰か外にいるようです。" },
      { pattern: "〜らしい", meaningEn: "apparently, I heard (based on outside information)", example: "彼は来月結婚するらしいです。" },
      { pattern: "〜ば", meaningEn: "if (conditional)", example: "安ければ買います。" },
      { pattern: "〜と（自然な結果）", meaningEn: "if...then always (natural or inevitable result)", example: "春になると、桜が咲きます。" },
      { pattern: "〜させる（使役形）", meaningEn: "causative: to make / let someone do", example: "先生は学生に本を読ませました。" },
      { pattern: "〜られる（受身形）", meaningEn: "passive: to be done to / to have something done to one", example: "犬に手をかまれました。" },
      { pattern: "〜ことにする", meaningEn: "to decide to (one's own decision)", example: "来年、日本へ行くことにしました。" },
      { pattern: "〜ことになる", meaningEn: "it has been decided that / it turns out that", example: "来月、大阪に転勤することになりました。" },
      { pattern: "〜つもりだ", meaningEn: "intend to", example: "夏休みに国へ帰るつもりです。" },
      { pattern: "〜だけ", meaningEn: "only, just", example: "お金が少しだけあります。" },
      { pattern: "〜しか〜ない", meaningEn: "nothing but ~ (emphatic negative)", example: "千円しかありません。" },
      { pattern: "〜くらい／ぐらい", meaningEn: "about, approximately", example: "駅まで十分くらいかかります。" },
      { pattern: "〜たことがある", meaningEn: "have done ~ before (experience)", example: "富士山に登ったことがあります。" },
    ],
    questions: [
      { category: "vocabulary", prompt: "「準備」の意味はどれですか。", choices: ["preparation", "invitation", "experience", "explanation"], correctIndex: 0, explanation: "「準備」= preparation。" },
      { category: "vocabulary", prompt: "「台風」の意味はどれですか。", choices: ["typhoon", "rainbow", "snow", "earthquake"], correctIndex: 0, explanation: "「台風」= typhoon。" },
      { category: "vocabulary", prompt: "「しょうたい」を漢字で書くとどれですか。", choices: ["招待", "紹介", "招介", "承知"], correctIndex: 0, explanation: "しょうたい = 招待 (invitation)。" },
      { category: "grammar", prompt: "「空が暗いです。雨が＿＿。」空欄に入るのはどれですか。", choices: ["降りそうです", "降ったら", "降るのに", "降りばかり"], correctIndex: 0, explanation: "見た目から予想する時は「〜そうです」。" },
      { category: "grammar", prompt: "「毎日練習して、漢字が読める＿＿なりました。」空欄に入るのはどれですか。", choices: ["ように", "そうに", "のに", "ばかりに"], correctIndex: 0, explanation: "「〜ようになる」= come to be able to。" },
      { category: "grammar", prompt: "「時間があっ＿＿、電話してください。」空欄に入るのはどれですか。", choices: ["たら", "ても", "のに", "ばかり"], correctIndex: 0, explanation: "「〜たら」= if / when。" },
      { category: "listening", prompt: "（会話）A「明日のパーティー、行きますか。」B「招待されたので、行くつもりです。」\n質問：Bさんはどうしますか。", choices: ["行かない", "行くつもりです", "考え中です", "招待していません"], correctIndex: 1, explanation: "「行くつもりです」と答えています。" },
      { category: "listening", prompt: "（会話）A「明日の天気はどうですか。」B「天気予報によると、台風が来るそうです。」\n質問：明日の天気はどうなりそうですか。", choices: ["晴れ", "台風が来る", "雪が降る", "変わらない"], correctIndex: 1, explanation: "「台風が来るそうです」と言っています。" },
      { category: "listening", prompt: "（会話）A「旅行の準備はできましたか。」B「いいえ、まだ用意していません。」\n質問：Bさんの旅行の準備はどうですか。", choices: ["終わった", "まだしていない", "半分終わった", "必要ない"], correctIndex: 1, explanation: "「まだ用意していません」と言っています。" },
      { category: "reading", prompt: "（文章）田中さんは海外で働いた経験があるので、英語で説明するのが上手です。\n質問：田中さんはなぜ英語の説明が上手ですか。", choices: ["学校で習ったから", "海外で働いた経験があるから", "本を読んだから", "先生だから"], correctIndex: 1, explanation: "「海外で働いた経験があるので」が理由です。" },
      { category: "reading", prompt: "（文章）今週末、台風が来るそうです。天気予報を見て、旅行の予定を変えるかもしれません。\n質問：なぜ予定を変えるかもしれませんか。", choices: ["友達がいないから", "台風が来るかもしれないから", "お金がないから", "仕事があるから"], correctIndex: 1, explanation: "台風が来るという予報のためです。" },
      { category: "reading", prompt: "（文章）山田さんは頑張って勉強したのに、試験に落ちてしまいました。\n質問：山田さんはどうでしたか。", choices: ["合格した", "頑張ったが不合格だった", "勉強しなかった", "試験を受けなかった"], correctIndex: 1, explanation: "「〜のに」は逆接：努力したのに結果が伴わなかった。" },
    ],
  },
  N3: {
    vocab: [
      { term: "影響", reading: "えいきょう", meaningJa: "他に及ぼす作用", meaningEn: "influence", example: "天気は気分に影響します。" },
      { term: "状況", reading: "じょうきょう", meaningJa: "その時の様子", meaningEn: "situation", example: "今の状況を説明してください。" },
      { term: "判断", reading: "はんだん", meaningJa: "考えて決めること", meaningEn: "judgment", example: "冷静に判断します。" },
      { term: "割合", reading: "わりあい", meaningJa: "全体に対する比率", meaningEn: "ratio / proportion", example: "女性の割合が増えています。" },
      { term: "環境", reading: "かんきょう", meaningJa: "周りの状態", meaningEn: "environment", example: "働く環境を整えます。" },
      { term: "対策", reading: "たいさく", meaningJa: "問題への対応", meaningEn: "countermeasure", example: "台風の対策をします。" },
      { term: "傾向", reading: "けいこう", meaningJa: "そうなりやすい性質", meaningEn: "tendency", example: "若者の傾向を調べます。" },
      { term: "維持", reading: "いじ", meaningJa: "そのまま保つこと", meaningEn: "maintenance", example: "健康を維持します。" },
    ],
    grammar: [
      { pattern: "〜わけではない", meaningEn: "doesn't necessarily mean", example: "嫌いなわけではありません。" },
      { pattern: "〜さえ〜ば", meaningEn: "as long as / if only", example: "時間さえあれば行けます。" },
      { pattern: "〜にとって", meaningEn: "for / from the perspective of", example: "学生にとって試験は大切です。" },
      { pattern: "〜おかげで", meaningEn: "thanks to", example: "先生のおかげで合格しました。" },
      { pattern: "〜つつある", meaningEn: "in the process of", example: "状況は改善しつつあります。" },
    ],
    questions: [
      { category: "vocabulary", prompt: "「判断」の意味はどれですか。", choices: ["judgment", "environment", "tendency", "maintenance"], correctIndex: 0, explanation: "「判断」= judgment。" },
      { category: "vocabulary", prompt: "「割合」の意味はどれですか。", choices: ["ratio / proportion", "influence", "countermeasure", "situation"], correctIndex: 0, explanation: "「割合」= ratio / proportion。" },
      { category: "vocabulary", prompt: "「たいさく」を漢字で書くとどれですか。", choices: ["対策", "対象", "体策", "対作"], correctIndex: 0, explanation: "たいさく = 対策 (countermeasure)。" },
      { category: "grammar", prompt: "「肉が嫌いな＿＿、あまり食べません。」空欄に入るのはどれですか。", choices: ["わけではありませんが", "さえあれば", "にとって", "おかげで"], correctIndex: 0, explanation: "「〜わけではない」= 部分否定。" },
      { category: "grammar", prompt: "「時間＿＿あれば、旅行に行けます。」空欄に入るのはどれですか。", choices: ["さえ", "こそ", "つつ", "ばかり"], correctIndex: 0, explanation: "「〜さえ〜ば」= as long as。" },
      { category: "grammar", prompt: "「先生の＿＿、無事に合格できました。」空欄に入るのはどれですか。", choices: ["おかげで", "せいで", "わけで", "うえで"], correctIndex: 0, explanation: "良い結果には「〜おかげで」を使います。" },
      { category: "listening", prompt: "（会話）A「最近、忙しいですか。」B「忙しいですが、嫌いなわけではありません。」\n質問：Bさんは仕事についてどう思っていますか。", choices: ["嫌いだ", "忙しいが嫌いではない", "楽だ", "辞めたい"], correctIndex: 1, explanation: "「嫌いなわけではありません」と言っています。" },
      { category: "listening", prompt: "（会話）A「環境問題について何か対策がありますか。」B「ゴミを減らす対策を進めています。」\n質問：どんな対策をしていますか。", choices: ["ゴミを減らす", "水を増やす", "電車を止める", "何もしない"], correctIndex: 0, explanation: "「ゴミを減らす対策」と言っています。" },
      { category: "listening", prompt: "（会話）A「景気はどうですか。」B「少しずつ回復しつつあります。」\n質問：景気の状況はどれですか。", choices: ["悪化している", "回復している最中", "完全に回復した", "変化がない"], correctIndex: 1, explanation: "「〜つつある」は進行中を表します。" },
      { category: "reading", prompt: "（文章）近年、リモートワークをする人の割合が増えている。働く環境が変わりつつあるといえる。\n質問：文章の内容と合っているのはどれですか。", choices: ["リモートワークは減っている", "働く環境は変化している", "環境は変わっていない", "誰も在宅勤務をしていない"], correctIndex: 1, explanation: "「働く環境が変わりつつある」とあります。" },
      { category: "reading", prompt: "（文章）今の状況を冷静に判断し、必要な対策を取ることが重要だ。\n質問：筆者が重要だと言っていることは何ですか。", choices: ["感情的に決めること", "冷静な判断と対策", "何もしないこと", "他人に任せること"], correctIndex: 1, explanation: "「冷静に判断し、対策を取ること」が重要だと述べています。" },
      { category: "reading", prompt: "（文章）健康を維持するためには、運動だけでなく食事や睡眠の管理も欠かせない。\n質問：健康維持に必要だと言われているのはどれですか。", choices: ["運動だけ", "運動・食事・睡眠", "睡眠だけ", "何も必要ない"], correctIndex: 1, explanation: "運動・食事・睡眠の管理が挙げられています。" },
    ],
  },
  N2: {
    vocab: [
      { term: "概念", reading: "がいねん", meaningJa: "物事の大まかな意味", meaningEn: "concept", example: "新しい概念を学びます。" },
      { term: "促進", reading: "そくしん", meaningJa: "物事を早く進めること", meaningEn: "promotion / acceleration", example: "経済の促進を図ります。" },
      { term: "抽象的", reading: "ちゅうしょうてき", meaningJa: "具体的でないこと", meaningEn: "abstract", example: "抽象的な説明では分かりません。" },
      { term: "一致", reading: "いっち", meaningJa: "同じになること", meaningEn: "agreement / match", example: "意見が一致しました。" },
      { term: "矛盾", reading: "むじゅん", meaningJa: "つじつまが合わないこと", meaningEn: "contradiction", example: "話に矛盾があります。" },
      { term: "補う", reading: "おぎなう", meaningJa: "足りない部分を満たす", meaningEn: "to compensate / supplement", example: "不足を補います。" },
      { term: "見なす", reading: "みなす", meaningJa: "そうだと判断する", meaningEn: "to regard as", example: "無回答は反対と見なします。" },
      { term: "妥協", reading: "だきょう", meaningJa: "譲り合って合意すること", meaningEn: "compromise", example: "お互いに妥協します。" },
    ],
    grammar: [
      { pattern: "〜にもかかわらず", meaningEn: "despite / in spite of", example: "努力したにもかかわらず失敗した。" },
      { pattern: "〜あげく", meaningEn: "after all (negative result)", example: "悩んだあげく、諦めた。" },
      { pattern: "〜を問わず", meaningEn: "regardless of", example: "経験を問わず応募できます。" },
      { pattern: "〜に応じて", meaningEn: "according to / in response to", example: "実力に応じてクラスを分けます。" },
      { pattern: "〜次第だ", meaningEn: "depends on", example: "成功するかは努力次第だ。" },
    ],
    questions: [
      { category: "vocabulary", prompt: "「矛盾」の意味はどれですか。", choices: ["contradiction", "compromise", "promotion", "concept"], correctIndex: 0, explanation: "「矛盾」= contradiction。" },
      { category: "vocabulary", prompt: "「抽象的」の反対の意味に近い言葉はどれですか。", choices: ["具体的", "促進的", "一致的", "妥協的"], correctIndex: 0, explanation: "抽象的 ⇔ 具体的。" },
      { category: "vocabulary", prompt: "「だきょう」を漢字で書くとどれですか。", choices: ["妥協", "妥協", "打境", "他協"], correctIndex: 0, explanation: "だきょう = 妥協 (compromise)。" },
      { category: "grammar", prompt: "「努力した＿＿、結果は出なかった。」空欄に入るのはどれですか。", choices: ["にもかかわらず", "を問わず", "に応じて", "次第だ"], correctIndex: 0, explanation: "「〜にもかかわらず」= despite。" },
      { category: "grammar", prompt: "「長時間悩んだ＿＿、計画を中止した。」空欄に入るのはどれですか。", choices: ["あげく", "にもかかわらず", "を問わず", "次第だ"], correctIndex: 0, explanation: "「〜あげく」= 悪い結果に至る経緯。" },
      { category: "grammar", prompt: "「参加資格は経験＿＿、誰でも応募できます。」空欄に入るのはどれですか。", choices: ["を問わず", "に応じて", "あげく", "次第だ"], correctIndex: 0, explanation: "「〜を問わず」= regardless of。" },
      { category: "listening", prompt: "（会話）A「新しいシステムの導入はどうですか。」B「業務の促進にとても役立っています。」\n質問：新システムはどう評価されていますか。", choices: ["役に立っている", "役に立っていない", "まだ導入していない", "反対されている"], correctIndex: 0, explanation: "「業務の促進に役立っている」と評価しています。" },
      { category: "listening", prompt: "（会話）A「彼の説明、分かりましたか。」B「いいえ、抽象的すぎて分かりませんでした。」\n質問：Bさんはなぜ分からなかったのですか。", choices: ["説明が具体的すぎたから", "説明が抽象的だったから", "説明を聞かなかったから", "興味がなかったから"], correctIndex: 1, explanation: "「抽象的すぎて」と理由を述べています。" },
      { category: "listening", prompt: "（会話）A「二人の意見は一致しましたか。」B「いいえ、最後はお互いに妥協しました。」\n質問：結果はどうなりましたか。", choices: ["完全に一致した", "妥協点を見つけた", "対立したままだ", "話し合いをやめた"], correctIndex: 1, explanation: "「お互いに妥協しました」と言っています。" },
      { category: "reading", prompt: "（文章）このデータには明らかな矛盾があり、報告書の内容をそのまま信用することはできない。\n質問：筆者は報告書についてどう考えていますか。", choices: ["完全に信頼できる", "矛盾があり信頼しにくい", "内容が正確だ", "何も問題がない"], correctIndex: 1, explanation: "「矛盾があり、信用できない」と述べています。" },
      { category: "reading", prompt: "（文章）給与は各人の実力に応じて決定される。年齢や経験年数を問わず、成果を重視する制度である。\n質問：この給与制度の特徴はどれですか。", choices: ["年齢を最も重視する", "実力・成果を重視する", "経験年数だけで決まる", "全員同じ給与になる"], correctIndex: 1, explanation: "「実力に応じて」「成果を重視」とあります。" },
      { category: "reading", prompt: "（文章）長時間の議論のあげく、両者は妥協案を受け入れることにした。\n質問：議論の結果はどうなりましたか。", choices: ["決裂した", "妥協案を受け入れた", "議論を続けている", "誰も納得しなかった"], correctIndex: 1, explanation: "「妥協案を受け入れることにした」とあります。" },
    ],
  },
  N1: {
    vocab: [
      { term: "曖昧", reading: "あいまい", meaningJa: "はっきりしないこと", meaningEn: "ambiguous / vague", example: "曖昧な返事をされました。" },
      { term: "遂行", reading: "すいこう", meaningJa: "物事をやり遂げること", meaningEn: "execution / carrying out", example: "任務を遂行します。" },
      { term: "円滑", reading: "えんかつ", meaningJa: "物事がスムーズに進むこと", meaningEn: "smooth", example: "円滑に進めます。" },
      { term: "是正", reading: "ぜせい", meaningJa: "誤りを正すこと", meaningEn: "correction / rectification", example: "格差を是正します。" },
      { term: "潜在的", reading: "せんざいてき", meaningJa: "表に出ていないこと", meaningEn: "potential / latent", example: "潜在的な needs があります。" },
      { term: "顕著", reading: "けんちょ", meaningJa: "はっきり目立つこと", meaningEn: "marked / prominent", example: "効果が顕著に表れました。" },
      { term: "逸脱", reading: "いつだつ", meaningJa: "本筋から外れること", meaningEn: "deviation", example: "規則から逸脱しています。" },
      { term: "秩序", reading: "ちつじょ", meaningJa: "正しい順序や決まり", meaningEn: "order", example: "社会の秩序を守ります。" },
    ],
    grammar: [
      { pattern: "〜きらいがある", meaningEn: "tend to (negative nuance)", example: "彼は結論を急ぐきらいがある。" },
      { pattern: "〜べからず", meaningEn: "must not", example: "立ち入るべからず。" },
      { pattern: "〜にたえない", meaningEn: "cannot bear to / cannot help but", example: "見るにたえない光景だ。" },
      { pattern: "〜ならでは", meaningEn: "unique to / only possible because of", example: "これは職人ならではの技術だ。" },
      { pattern: "〜を余儀なくされる", meaningEn: "be forced to", example: "計画の中止を余儀なくされた。" },
    ],
    questions: [
      { category: "vocabulary", prompt: "「曖昧」の意味はどれですか。", choices: ["ambiguous / vague", "smooth", "prominent", "orderly"], correctIndex: 0, explanation: "「曖昧」= ambiguous / vague。" },
      { category: "vocabulary", prompt: "「顕著」の意味はどれですか。", choices: ["marked / prominent", "latent", "smooth", "deviant"], correctIndex: 0, explanation: "「顕著」= marked / prominent。" },
      { category: "vocabulary", prompt: "「ぜせい」を漢字で書くとどれですか。", choices: ["是正", "是製", "制正", "是政"], correctIndex: 0, explanation: "ぜせい = 是正 (correction)。" },
      { category: "grammar", prompt: "「彼の説明は要点が＿＿きらいがある。」空欄に入るのはどれですか。", choices: ["ずれる", "ずれた", "ずれて", "ずれ"], correctIndex: 0, explanation: "「〜きらいがある」の前は動詞辞書形。" },
      { category: "grammar", prompt: "「その惨状は目を覆う＿＿ものだった。」空欄に入るのはどれですか。", choices: ["にたえない", "べからず", "ならでは", "を余儀なくされる"], correctIndex: 0, explanation: "「〜にたえない」= 直視できないほど酷い。" },
      { category: "grammar", prompt: "「台風のため、イベントの中止＿＿。」空欄に入るのはどれですか。", choices: ["を余儀なくされた", "にたえない", "べからず", "きらいがある"], correctIndex: 0, explanation: "「〜を余儀なくされる」= 強制的にそうせざるを得ない。" },
      { category: "listening", prompt: "（会話）A「今回のプロジェクトは順調ですか。」B「はい、想定より円滑に進んでいます。」\n質問：プロジェクトの状況はどれですか。", choices: ["問題が多い", "順調に進んでいる", "中止になった", "遅れている"], correctIndex: 1, explanation: "「円滑に進んでいます」と答えています。" },
      { category: "listening", prompt: "（会話）A「彼の返答についてどう思いますか。」B「正直、曖昧で判断しかねます。」\n質問：Bさんは彼の返答をどう感じていますか。", choices: ["明確だ", "曖昧で分かりにくい", "とても具体的だ", "満足している"], correctIndex: 1, explanation: "「曖昧で判断しかねます」と述べています。" },
      { category: "listening", prompt: "（会話）A「規則から逸脱した行為があったそうですね。」B「はい、社内で秩序を是正する動きが出ています。」\n質問：社内ではどんな動きがありますか。", choices: ["規則を廃止する", "秩序を是正しようとしている", "何もしない", "逸脱を推奨する"], correctIndex: 1, explanation: "「秩序を是正する動き」と言っています。" },
      { category: "reading", prompt: "（文章）本制度は潜在的な需要を掘り起こすことを目的としており、効果はすでに顕著に表れている。\n質問：この文章の内容と合っているのはどれですか。", choices: ["効果はまだ出ていない", "効果ははっきり表れている", "制度は失敗した", "需要は存在しない"], correctIndex: 1, explanation: "「効果はすでに顕著に表れている」とあります。" },
      { category: "reading", prompt: "（文章）予期せぬ事態により、当初の計画は大幅な変更を余儀なくされたが、関係者の努力により業務は円滑に遂行された。\n質問：業務の結果はどうでしたか。", choices: ["計画通りに何も変えず進んだ", "変更を強いられたが円滑に遂行された", "完全に失敗した", "誰も対応しなかった"], correctIndex: 1, explanation: "「変更を余儀なくされたが、円滑に遂行された」とあります。" },
      { category: "reading", prompt: "（文章）彼の主張には根拠が乏しく、事実から逸脱しているきらいがあるため、慎重に検討すべきだ。\n質問：筆者は彼の主張をどう見ていますか。", choices: ["信頼できると評価している", "事実から外れている可能性を懸念している", "全く興味がない", "秩序があると称賛している"], correctIndex: 1, explanation: "「事実から逸脱しているきらいがある」と懸念を示しています。" },
    ],
  },
};