import type { Dictionary } from "../types";

const mn: Dictionary = {
  category: { vocabulary: "Үгийн сан", grammar: "Дүрэм", listening: "Сонсох", listeningFull: "Сонсох (бичвэртэй)", reading: "Унших" },
  learnerHome: { currentLevel: "Одоогийн түвшин", target: "Зорилго", aiAnalysis: "AI дүн шинжилгээг харах", backToProfiles: "Профайл сонголт руу буцах", aiCoachNote: "Таны AI дасгалжуулагчийн тэмдэглэл", chooseLevel: "Түвшин сонгох", accuracyWithCount: "{pct}% зөв ({total} асуулт)", notAttempted: "Хараахан оролдоогүй байна" },
  level: { backToHome: "← {name}-ийн нүүр хуудас руу буцах", levelSuffix: "түвшин", tryQuiz: "Шалгалт өгөх", questionsCount: "10 асуулт", comprehensiveQuiz: "Иж бүрэн шалгалт", randomAllCategories: "Бүх ангиллаас санамсаргүй асуултууд", vocabListTitle: "Үгийн сангийн жагсаалт (жишээ)", grammarListTitle: "Дүрмийн жагсаалт (жишээ)", example: "Жишээ:" },
  quiz: { loading: "Асуултуудыг ачааллаж байна...", noQuestionsFound: "Эдгээр тохиргоонд тохирох шалгалтын асуулт олдсонгүй.", loadFailed: "Асуултуудыг ачааллаж чадсангүй.", backToLevel: "Түвшний хуудас руу буцах", resultsOf: "{name}-ийн дүн", correct: "Зөв", incorrect: "Буруу", correctAnswer: "Зөв хариулт: {answer}", next: "Дараах", scoreButton: "Илгээх", scoring: "Дүгнэж байна...", aiAnalysis: "AI дүн шинжилгээг харах" },
  analytics: { backToHome: "← {name}-ийн нүүр хуудас руу буцах", title: "AI ахицын дүн шинжилгээ", refresh: "Дүн шинжилгээг шинэчлэх", refreshing: "Шинэчилж байна...", coachAnalysis: "AI дасгалжуулагчийн дүн шинжилгээ", lastUpdated: "Сүүлд шинэчилсэн: {date}", weakStrongTitle: "Давуу болон сул талууд", weakStrongSubtitle: "Ангилал тус бүрийн зөв хариултын хувь", paceTitle: "Тэнцэх магадлал ба суралцах хурд", trendTitle: "Ахицын чиг хандлага (сүүлийн 30 хоног)", trendSubtitle: "Өдөр тутмын зөв хариултын хувь", recommendationsTitle: "Цаашид юу судлах вэ" },
  gauge: { statusGood: "Зорилгын дагуу явж байна", statusWarning: "Бараг хүрлээ", statusSerious: "Дахин үзэх шаардлагатай", statusCritical: "Анхаарал хандуулах шаардлагатай", weeksEstimate: "Зорилгодоо хүрэхэд ойролцоогоор {weeks} долоо хоног шаардагдана." },
  lineChart: { noData: "Одоогоор суралцсан бүртгэл алга байна. Шалгалт өгвөл өдөр тутмын зөв хариултын хувь энд харагдана.", showTable: "Хүснэгт харуулах", hideTable: "Хүснэгт нуух", tooltipAccuracy: "{pct}% зөв ({correct}/{attempts} асуулт)", colDate: "Огноо", colAttempts: "Оролдлого", colCorrect: "Зөв", colAccuracy: "Нарийвчлал" },
  narrative: { noAttempts: "Одоогоор шалгалтын түүх алга байна. Түвшин сонгож, шалгалт өгч эхлээрэй — өгөгдөл хуримтлагдмагц AI таны сул талууд болон суралцах хурдыг дүн шинжилгээ хийх болно.", summary: "Та одоогоор {total} асуултад хариулж, {acc}% зөв хариулсан байна ({days} өдөр идэвхтэй байсан).", weakest: "{category}-д таны зөв хариултын хувь бусдаас бага байгаа тул энэ хэсгийг эхлээд дахин үзвэл зохино.", strongest: "Та {category}-д сайн байна — үргэлжлүүлээрэй.", paceKnown: "Одоогийн хурдаараа та {target}-д ойролцоогоор {weeks} долоо хоногийн дараа хүрнэ гэж тооцоолж байгаа бөгөөд тэнцэх магадлал ойролцоогоор {pct}% байна.", paceUnknown: "Хурдыг тооцоолохын тулд хэдэн шалгалт нэмж өгөх шаардлагатай.", streak: "Та одоогоор {days} өдөр дараалан хичээллэж байна.", weakVocabItem: "Та ялангуяа \"{term}\" ({meaning}) гэдэг үгийг андуурдаг тул давтаж үзэхийг зөвлөж байна.", weakGrammarItem: "Дүрмийн хувьд \"{pattern}\" ({meaning})-г дахин нягтлан үзвэл зохимжтой." },
  pace: { levelReached: "Та зорилтот түвшиндээ хүрсэн байна. Үүнийгээ хадгалахын тулд үргэлжлүүлэн давтаарай.", note: "Энэ нь таны одоогийн хурдад үндэслэсэн тооцоо юм (найдвартай байдал: {confidence}).", needMoreData: "Шалгалтын түүх хараахан цөөн байна — найдвартай тооцоо гаргахын тулд хэдэн шалгалт нэмж өгөх шаардлагатай.", confidenceLow: "бага", confidenceMedium: "дунд", confidenceHigh: "өндөр" },
  recommendations: { reviewWeakestTitle: "{category}-г дахин үзэхэд анхаарлаа хандуулаарай", reviewWeakestDescription: "Тэнд таны сүүлийн үеийн зөв хариултын хувь {pct}% байна. Санаж үлдэхийн тулд ижил ангиллаар дахин оролдоод үзээрэй.", tryComprehensiveTitle: "{level} түвшний иж бүрэн шалгалт өгч үзээрэй", tryComprehensiveDescription: "Одоогийн байдлаа мэдэхийн тулд бүх ангиллыг хамарсан шалгалтаас эхлээрэй.", vocabReviewTitle: "{level} түвшний үгийн сангийн жагсаалтыг дахин үзээрэй", vocabReviewDescription: "{count} үгийг үзэж, өөртөө итгэлтэй биш үгсэд анхаарлаа хандуулаарай.", grammarReviewTitle: "{level} түвшний дүрмийн загваруудыг дахин үзээрэй", grammarReviewDescription: "{count} загварыг жишээ өгүүлбэрүүдийн хамт дахин үзээрэй.", levelUpTitle: "{level} түвшинд шилжихэд бэлэн боллоо", levelUpDescription: "Таны {current} дэх зөв хариултын хувь тогтвортой байна — дараа нь {level} түвшний шалгалт өгч үзээрэй." },
  studyTime: { title: "Хичээллэсэн хугацаа", totalLabel: "Нийт хичээллэсэн хугацаа", todayLabel: "Өнөөдөр", weekLabel: "Энэ долоо хоног", streakLabel: "Дараалан хичээллэсэн өдөр", streakDays: "{days} өдөр", trendTitle: "Хичээллэсэн хугацааны чиг хандлага (сүүлийн 30 өдөр)", trendSubtitle: "Өдөр бүр хичээллэсэн минут", minutesUnit: "{minutes} мин", hoursMinutesUnit: "{hours} цаг {minutes} мин", noStreak: "Хичээллэсэн бүртгэл одоогоор алга", noData: "Хичээллэсэн хугацааны бүртгэл одоогоор алга байна. Асуулга эсвэл үгийн жагсаалтыг нээмэгц бүртгэл эхэлнэ." },
  weakItems: { title: "Сул тал болох үг, дүрэм", subtitle: "Та байнга андуурдаг зүйлс — сайтар давтаж үзвэл зохино.", vocabTitle: "Давтах ёстой үгс", grammarTitle: "Давтах ёстой дүрэм", missedCount: "{count} удаа андуурсан", noWeakVocab: "Сул тал болох үг одоогоор илрээгүй байна.", noWeakGrammar: "Сул тал болох дүрэм одоогоор илрээгүй байна." },
};

export default mn;