import type { Dictionary } from "../types";

const th: Dictionary = {
  category: { vocabulary: "คำศัพท์", grammar: "ไวยากรณ์", listening: "การฟัง", listeningFull: "การฟัง (พร้อมบทถอดเสียง)", reading: "การอ่าน" },
  learnerHome: { currentLevel: "ระดับปัจจุบัน", target: "เป้าหมาย", aiAnalysis: "ดูการวิเคราะห์โดย AI", backToProfiles: "กลับไปหน้าเลือกโปรไฟล์", aiCoachNote: "ข้อความจากโค้ช AI ของคุณ", chooseLevel: "เลือกระดับ", accuracyWithCount: "ถูกต้อง {pct}% ({total} ข้อ)", notAttempted: "ยังไม่ได้ทำแบบทดสอบ" },
  level: { backToHome: "← กลับไปหน้าหลักของ {name}", levelSuffix: "ระดับ", tryQuiz: "ลองทำแบบทดสอบ", questionsCount: "10 ข้อ", comprehensiveQuiz: "แบบทดสอบรวม", randomAllCategories: "คำถามสุ่มจากทุกหมวดหมู่", vocabListTitle: "รายการคำศัพท์ (ตัวอย่าง)", grammarListTitle: "รายการไวยากรณ์ (ตัวอย่าง)", example: "ตัวอย่าง:" },
  quiz: { loading: "กำลังโหลดคำถาม...", noQuestionsFound: "ไม่พบคำถามแบบทดสอบสำหรับการตั้งค่านี้", loadFailed: "โหลดคำถามไม่สำเร็จ", backToLevel: "กลับไปหน้าระดับ", resultsOf: "ผลคะแนนของ {name}", correct: "ถูกต้อง", incorrect: "ไม่ถูกต้อง", correctAnswer: "คำตอบที่ถูกต้อง: {answer}", next: "ถัดไป", scoreButton: "ส่งคำตอบ", scoring: "กำลังตรวจคะแนน...", aiAnalysis: "ดูการวิเคราะห์โดย AI" },
  analytics: { backToHome: "← กลับไปหน้าหลักของ {name}", title: "การวิเคราะห์ความก้าวหน้าโดย AI", refresh: "รีเฟรชการวิเคราะห์", refreshing: "กำลังรีเฟรช...", coachAnalysis: "การวิเคราะห์โดยโค้ช AI", lastUpdated: "อัปเดตล่าสุด: {date}", weakStrongTitle: "จุดแข็งและจุดอ่อน", weakStrongSubtitle: "ความแม่นยำแยกตามหมวดหมู่", paceTitle: "โอกาสสอบผ่านและความเร็วในการเรียนรู้", trendTitle: "แนวโน้มความก้าวหน้า (30 วันล่าสุด)", trendSubtitle: "ความแม่นยำรายวัน", recommendationsTitle: "สิ่งที่ควรเรียนต่อไป" },
  gauge: { statusGood: "เป็นไปตามแผน", statusWarning: "ใกล้ถึงเป้าหมายแล้ว", statusSerious: "ควรทบทวน", statusCritical: "ต้องให้ความสำคัญเป็นพิเศษ", weeksEstimate: "คาดว่าจะถึงเป้าหมายของคุณในประมาณ {weeks} สัปดาห์" },
  lineChart: { noData: "ยังไม่มีประวัติการเรียน ลองทำแบบทดสอบดู แล้วความแม่นยำรายวันของคุณจะแสดงที่นี่", showTable: "แสดงตาราง", hideTable: "ซ่อนตาราง", tooltipAccuracy: "ถูกต้อง {pct}% ({correct}/{attempts} ข้อ)", colDate: "วันที่", colAttempts: "จำนวนที่ทำ", colCorrect: "ถูกต้อง", colAccuracy: "ความแม่นยำ" },
  narrative: { noAttempts: "ยังไม่มีประวัติการทำแบบทดสอบ เลือกระดับแล้วลองทำแบบทดสอบเพื่อเริ่มต้น — AI จะวิเคราะห์จุดอ่อนและความเร็วในการเรียนรู้ของคุณเมื่อมีข้อมูลมากขึ้น", summary: "คุณตอบคำถามไปแล้ว {total} ข้อ ด้วยความแม่นยำ {acc}% (เรียนรู้ทั้งหมด {days} วัน)", weakest: "ความแม่นยำของคุณในหมวด {category} ต่ำกว่าหมวดอื่นเล็กน้อย จึงควรทบทวนหมวดนี้ก่อน", strongest: "คุณทำได้ดีในหมวด {category} — ทำต่อไปแบบนี้", paceKnown: "ด้วยความเร็วในการเรียนรู้ปัจจุบัน คาดว่าคุณจะถึงระดับ {target} ในประมาณ {weeks} สัปดาห์ โดยมีโอกาสสอบผ่านประมาณ {pct}%", paceUnknown: "ต้องทำแบบทดสอบเพิ่มอีกสักหน่อยก่อนจึงจะสามารถประเมินความเร็วในการเรียนรู้ได้" },
  pace: { levelReached: "คุณถึงระดับเป้าหมายแล้ว ทบทวนต่อไปเพื่อรักษาระดับนี้ไว้", note: "นี่เป็นการประมาณการจากความเร็วในการเรียนรู้ปัจจุบันของคุณ (ความมั่นใจ: {confidence})", needMoreData: "ยังมีประวัติการทำแบบทดสอบไม่มากนัก ต้องทำแบบทดสอบเพิ่มอีกสักหน่อยเพื่อให้การประมาณการแม่นยำขึ้น", confidenceLow: "ต่ำ", confidenceMedium: "ปานกลาง", confidenceHigh: "สูง" },
  recommendations: { reviewWeakestTitle: "เน้นทบทวนหมวด {category}", reviewWeakestDescription: "ความแม่นยำล่าสุดของคุณในหมวดนี้อยู่ที่ {pct}% ลองทำแบบทดสอบหมวดเดิมอีกครั้งเพื่อให้จำได้แม่นยำขึ้น", tryComprehensiveTitle: "ลองทำแบบทดสอบรวมระดับ {level}", tryComprehensiveDescription: "เริ่มต้นด้วยแบบทดสอบที่ครอบคลุมทุกหมวดหมู่ เพื่อดูว่าตอนนี้คุณอยู่ในระดับไหน", vocabReviewTitle: "ทบทวนรายการคำศัพท์ระดับ {level}", vocabReviewDescription: "ทบทวนคำศัพท์ทั้ง {count} คำ โดยเน้นคำที่คุณยังไม่มั่นใจ", grammarReviewTitle: "ทบทวนรูปแบบไวยากรณ์ระดับ {level}", grammarReviewDescription: "ทบทวนรูปแบบไวยากรณ์ทั้ง {count} รูปแบบ พร้อมประโยคตัวอย่าง", levelUpTitle: "พร้อมก้าวสู่ระดับ {level}", levelUpDescription: "ความแม่นยำของคุณในระดับ {current} ค่อนข้างคงที่แล้ว — ลองทำแบบทดสอบระดับ {level} ต่อไป" },
};

export default th;