import type { Dictionary } from "../types";

const tl: Dictionary = {
  category: { vocabulary: "Bokabularyo", grammar: "Balarila", listening: "Pakikinig", listeningFull: "Pakikinig (may transcript)", reading: "Pagbasa" },
  learnerHome: { currentLevel: "Kasalukuyang antas", target: "Target", aiAnalysis: "Tingnan ang AI analysis", backToProfiles: "Bumalik sa pagpili ng profile", aiCoachNote: "Tala mula sa iyong AI coach", chooseLevel: "Pumili ng antas", accuracyWithCount: "{pct}% tama ({total} na tanong)", notAttempted: "Hindi pa nasusubukan" },
  level: { backToHome: "← Bumalik sa home ni {name}", levelSuffix: "antas", tryQuiz: "Sumubok ng quiz", questionsCount: "10 tanong", comprehensiveQuiz: "Komprehensibong quiz", randomAllCategories: "Random na tanong mula sa lahat ng kategorya", vocabListTitle: "Listahan ng bokabularyo (sample)", grammarListTitle: "Listahan ng balarila (sample)", example: "Halimbawa:" },
  quiz: { loading: "Nilo-load ang mga tanong...", noQuestionsFound: "Walang nahanap na tanong para sa mga setting na ito.", loadFailed: "Nabigo ang pag-load ng mga tanong.", backToLevel: "Bumalik sa pahina ng antas", resultsOf: "Resulta ni {name}", correct: "Tama", incorrect: "Mali", correctAnswer: "Tamang sagot: {answer}", next: "Susunod", scoreButton: "Isumite", scoring: "Kinukuwenta ang score...", aiAnalysis: "Tingnan ang AI analysis" },
  analytics: { backToHome: "← Bumalik sa home ni {name}", title: "AI progress analysis", refresh: "I-refresh ang analysis", refreshing: "Nire-refresh...", coachAnalysis: "Analysis ng AI coach", lastUpdated: "Huling na-update: {date}", weakStrongTitle: "Mga kalakasan at kahinaan", weakStrongSubtitle: "Katumpakan ayon sa kategorya", paceTitle: "Posibilidad na makapasa at bilis ng pag-aaral", trendTitle: "Takbo ng progreso (huling 30 araw)", trendSubtitle: "Pang-araw-araw na katumpakan", recommendationsTitle: "Ano ang susunod na dapat pag-aralan" },
  gauge: { statusGood: "Nasa tamang landas", statusWarning: "Malapit na", statusSerious: "Kailangan ng review", statusCritical: "Kailangan ng agarang atensyon", weeksEstimate: "Tinatayang aabutin ng humigit-kumulang {weeks} linggo bago marating ang iyong target." },
  lineChart: { noData: "Wala pang record ng pag-aaral. Sumubok ng quiz at lalabas dito ang iyong pang-araw-araw na katumpakan.", showTable: "Ipakita ang table", hideTable: "Itago ang table", tooltipAccuracy: "{pct}% tama ({correct}/{attempts} na tanong)", colDate: "Petsa", colAttempts: "Bilang ng pagsubok", colCorrect: "Tama", colAccuracy: "Katumpakan" },
  narrative: { noAttempts: "Wala pang history ng quiz. Pumili ng antas at sumubok ng quiz para magsimula — susuriin ng AI ang iyong mga kahinaan at bilis ng pag-aaral kapag mayroon nang datos.", summary: "Nakasagot ka na ng {total} tanong sa ngayon na may {acc}% katumpakan (aktibo sa loob ng {days} araw).", weakest: "Bahagyang mas mababa ang iyong katumpakan sa {category} kumpara sa iba, kaya mainam munang balikan ang bahaging ito.", strongest: "Magaling ka sa {category} — ituloy mo lang.", paceKnown: "Sa kasalukuyan mong bilis, tinatantya na maaabot mo ang {target} sa loob ng humigit-kumulang {weeks} linggo, na may humigit-kumulang {pct}% na posibilidad na makapasa.", paceUnknown: "Kailangan pa ng ilang quiz bago matantya ang bilis ng pag-aaral." },
  pace: { levelReached: "Naabot mo na ang iyong target na antas. Ipagpatuloy ang pag-review para mapanatili ito.", note: "Ito ay isang tantiya batay sa iyong kasalukuyang bilis (kumpiyansa: {confidence}).", needMoreData: "Kaunti pa lang ang history ng quiz — kailangan pa ng ilang quiz para sa mas maaasahang tantiya.", confidenceLow: "mababa", confidenceMedium: "katamtaman", confidenceHigh: "mataas" },
  recommendations: { reviewWeakestTitle: "Mag-focus sa pag-review ng {category}", reviewWeakestDescription: "Ang iyong kamakailang katumpakan doon ay {pct}%. Subukan muli ang parehong kategorya para mas matatak ito.", tryComprehensiveTitle: "Subukan ang komprehensibong quiz ng {level}", tryComprehensiveDescription: "Magsimula sa isang quiz na sumasaklaw sa lahat ng kategorya para makita kung nasaan ka ngayon.", vocabReviewTitle: "I-review ang listahan ng bokabularyo ng {level}", vocabReviewDescription: "Balikan ang {count} salita, na may pokus sa mga hindi mo pa gaanong kumpiyansa.", grammarReviewTitle: "I-review ang mga grammar pattern ng {level}", grammarReviewDescription: "Suriin ang {count} pattern kasama ang kanilang mga halimbawang pangungusap.", levelUpTitle: "Handa nang lumipat sa {level}", levelUpDescription: "Matatag ang iyong katumpakan sa {current} — subukan ang quiz ng {level} sa susunod." },
};

export default tl;