import type { Dictionary } from "../types";

const vi: Dictionary = {
  category: { vocabulary: "Từ vựng", grammar: "Ngữ pháp", listening: "Nghe", listeningFull: "Nghe (có bản ghi)", reading: "Đọc hiểu" },
  learnerHome: { currentLevel: "Trình độ hiện tại", target: "Mục tiêu", aiAnalysis: "Xem phân tích AI", backToProfiles: "Quay lại chọn hồ sơ", aiCoachNote: "Lời nhắn từ huấn luyện viên AI của bạn", chooseLevel: "Chọn trình độ", accuracyWithCount: "Đúng {pct}% ({total} câu hỏi)", notAttempted: "Chưa làm bài" },
  level: { backToHome: "← Quay lại trang chủ của {name}", levelSuffix: "cấp độ", tryQuiz: "Làm thử bài kiểm tra", questionsCount: "10 câu hỏi", comprehensiveQuiz: "Bài kiểm tra tổng hợp", randomAllCategories: "Câu hỏi ngẫu nhiên từ tất cả các danh mục", vocabListTitle: "Danh sách từ vựng (mẫu)", grammarListTitle: "Danh sách ngữ pháp (mẫu)", example: "Ví dụ:" },
  quiz: { loading: "Đang tải câu hỏi...", noQuestionsFound: "Không tìm thấy câu hỏi nào cho các thiết lập này.", loadFailed: "Không thể tải câu hỏi.", backToLevel: "Quay lại trang trình độ", resultsOf: "Kết quả của {name}", correct: "Đúng", incorrect: "Sai", correctAnswer: "Đáp án đúng: {answer}", next: "Tiếp theo", scoreButton: "Nộp bài", scoring: "Đang chấm điểm...", aiAnalysis: "Xem phân tích AI" },
  analytics: { backToHome: "← Quay lại trang chủ của {name}", title: "Phân tích tiến độ bằng AI", refresh: "Làm mới phân tích", refreshing: "Đang làm mới...", coachAnalysis: "Phân tích của huấn luyện viên AI", lastUpdated: "Cập nhật lần cuối: {date}", weakStrongTitle: "Điểm mạnh & điểm yếu", weakStrongSubtitle: "Độ chính xác theo danh mục", paceTitle: "Khả năng đạt & tốc độ học", trendTitle: "Xu hướng tiến bộ (30 ngày qua)", trendSubtitle: "Độ chính xác hằng ngày", recommendationsTitle: "Nên học gì tiếp theo" },
  gauge: { statusGood: "Đúng tiến độ", statusWarning: "Sắp đạt được", statusSerious: "Cần ôn lại", statusCritical: "Cần chú ý", weeksEstimate: "Ước tính khoảng {weeks} tuần để đạt được mục tiêu của bạn." },
  lineChart: { noData: "Chưa có dữ liệu học tập. Hãy làm một bài kiểm tra và độ chính xác hằng ngày của bạn sẽ hiển thị ở đây.", showTable: "Hiện bảng", hideTable: "Ẩn bảng", tooltipAccuracy: "Đúng {pct}% ({correct}/{attempts} câu hỏi)", colDate: "Ngày", colAttempts: "Số lần làm", colCorrect: "Số câu đúng", colAccuracy: "Độ chính xác" },
  narrative: { noAttempts: "Bạn chưa có lịch sử làm bài. Hãy chọn một trình độ và làm thử một bài kiểm tra để bắt đầu — AI sẽ phân tích điểm yếu và tốc độ học của bạn khi có đủ dữ liệu.", summary: "Bạn đã trả lời {total} câu hỏi với độ chính xác {acc}% (đã học trong {days} ngày).", weakest: "Độ chính xác của bạn trong phần {category} thấp hơn một chút so với các phần khác, vì vậy bạn nên ôn tập phần này trước.", strongest: "Bạn đang làm rất tốt ở phần {category} — hãy tiếp tục phát huy.", paceKnown: "Với tốc độ hiện tại, bạn được ước tính sẽ đạt {target} trong khoảng {weeks} tuần, với khả năng đạt khoảng {pct}%.", paceUnknown: "Cần làm thêm vài bài kiểm tra nữa để có thể ước tính tốc độ học." },
  pace: { levelReached: "Bạn đã đạt được trình độ mục tiêu. Hãy tiếp tục ôn tập để duy trì trình độ này.", note: "Đây là ước tính dựa trên tốc độ học hiện tại của bạn (độ tin cậy: {confidence}).", needMoreData: "Hiện chưa có nhiều lịch sử làm bài — cần làm thêm vài bài kiểm tra nữa để có ước tính đáng tin cậy.", confidenceLow: "thấp", confidenceMedium: "trung bình", confidenceHigh: "cao" },
  recommendations: { reviewWeakestTitle: "Tập trung ôn tập phần {category}", reviewWeakestDescription: "Độ chính xác gần đây của bạn ở phần này là {pct}%. Hãy thử lại danh mục này để ghi nhớ tốt hơn.", tryComprehensiveTitle: "Thử bài kiểm tra tổng hợp trình độ {level}", tryComprehensiveDescription: "Bắt đầu với một bài kiểm tra bao quát tất cả các danh mục để biết trình độ hiện tại của bạn.", vocabReviewTitle: "Ôn tập danh sách từ vựng trình độ {level}", vocabReviewDescription: "Xem lại {count} từ, tập trung vào những từ bạn chưa tự tin.", grammarReviewTitle: "Ôn tập các mẫu ngữ pháp trình độ {level}", grammarReviewDescription: "Xem lại {count} mẫu ngữ pháp cùng với các câu ví dụ.", levelUpTitle: "Sẵn sàng chuyển sang trình độ {level}", levelUpDescription: "Độ chính xác của bạn ở trình độ {current} đã ổn định — hãy thử làm bài kiểm tra {level} tiếp theo." },
};

export default vi;