import type { Dictionary } from "../types";

const id: Dictionary = {
  category: {
    vocabulary: "Kosakata",
    grammar: "Tata Bahasa",
    listening: "Mendengarkan",
    listeningFull: "Mendengarkan (dengan transkrip)",
    reading: "Membaca",
  },
  learnerHome: {
    currentLevel: "Level saat ini",
    target: "Target",
    aiAnalysis: "Lihat analisis AI",
    backToProfiles: "Kembali ke pilihan profil",
    aiCoachNote: "Catatan dari pelatih AI Anda",
    chooseLevel: "Pilih level",
    accuracyWithCount: "{pct}% benar ({total} soal)",
    notAttempted: "Belum dicoba",
  },
  level: {
    backToHome: "← Kembali ke beranda {name}",
    levelSuffix: "level",
    tryQuiz: "Coba kuis",
    questionsCount: "10 soal",
    comprehensiveQuiz: "Kuis komprehensif",
    randomAllCategories: "Soal acak dari semua kategori",
    vocabListTitle: "Daftar kosakata (contoh)",
    grammarListTitle: "Daftar tata bahasa (contoh)",
    example: "Contoh:",
  },
  quiz: {
    loading: "Memuat soal...",
    noQuestionsFound: "Tidak ada soal kuis yang ditemukan untuk pengaturan ini.",
    loadFailed: "Gagal memuat soal.",
    backToLevel: "Kembali ke halaman level",
    resultsOf: "Hasil {name}",
    correct: "Benar",
    incorrect: "Salah",
    correctAnswer: "Jawaban yang benar: {answer}",
    next: "Berikutnya",
    scoreButton: "Kirim",
    scoring: "Menilai...",
    aiAnalysis: "Lihat analisis AI",
  },
  analytics: {
    backToHome: "← Kembali ke beranda {name}",
    title: "Analisis kemajuan AI",
    refresh: "Perbarui analisis",
    refreshing: "Memperbarui...",
    coachAnalysis: "Analisis pelatih AI",
    lastUpdated: "Terakhir diperbarui: {date}",
    weakStrongTitle: "Kelebihan & kekurangan",
    weakStrongSubtitle: "Akurasi berdasarkan kategori",
    paceTitle: "Peluang lulus & kecepatan belajar",
    trendTitle: "Tren kemajuan (30 hari terakhir)",
    trendSubtitle: "Akurasi harian",
    recommendationsTitle: "Yang perlu dipelajari selanjutnya",
  },
  gauge: {
    statusGood: "Sesuai jalur",
    statusWarning: "Hampir tercapai",
    statusSerious: "Perlu ditinjau ulang",
    statusCritical: "Perlu perhatian",
    weeksEstimate: "Diperkirakan sekitar {weeks} minggu lagi untuk mencapai target Anda.",
  },
  lineChart: {
    noData: "Belum ada catatan belajar. Coba kerjakan kuis dan akurasi harian Anda akan muncul di sini.",
    showTable: "Tampilkan tabel",
    hideTable: "Sembunyikan tabel",
    tooltipAccuracy: "{pct}% benar ({correct}/{attempts} soal)",
    colDate: "Tanggal",
    colAttempts: "Percobaan",
    colCorrect: "Benar",
    colAccuracy: "Akurasi",
  },
  narrative: {
    noAttempts: "Belum ada riwayat kuis. Pilih level dan coba kuis untuk memulai — AI akan menganalisis kelemahan dan kecepatan belajar Anda setelah ada cukup data.",
    summary: "Anda telah menjawab {total} soal sejauh ini dengan akurasi {acc}% (aktif selama {days} hari).",
    weakest: "Akurasi Anda dalam {category} sedikit lebih rendah dibanding yang lain, jadi ada baiknya meninjau ulang bagian ini terlebih dahulu.",
    strongest: "Anda sudah baik dalam {category} — pertahankan.",
    paceKnown: "Dengan kecepatan Anda saat ini, diperkirakan Anda akan mencapai {target} dalam sekitar {weeks} minggu, dengan peluang lulus sekitar {pct}%.",
    paceUnknown: "Diperlukan beberapa kuis lagi sebelum kecepatan belajar dapat diperkirakan.", streak: "Anda sedang mempertahankan rekor belajar {days} hari berturut-turut.", weakVocabItem: "Anda sering salah pada kata \"{term}\" ({meaning}) — sebaiknya ditinjau kembali.", weakGrammarItem: "Untuk tata bahasa, \"{pattern}\" ({meaning}) sebaiknya dipelajari lagi." },
  pace: {
    levelReached: "Anda sudah mencapai level target Anda. Teruskan meninjau ulang untuk mempertahankannya.",
    note: "Ini adalah perkiraan berdasarkan kecepatan Anda saat ini (tingkat keyakinan: {confidence}).",
    needMoreData: "Riwayat kuis masih belum banyak — diperlukan beberapa kuis lagi untuk perkiraan yang lebih akurat.",
    confidenceLow: "rendah",
    confidenceMedium: "sedang",
    confidenceHigh: "tinggi",
  },
  recommendations: {
    reviewWeakestTitle: "Fokus meninjau ulang {category}",
    reviewWeakestDescription: "Akurasi Anda di bagian ini baru-baru ini adalah {pct}%. Coba kategori yang sama lagi agar lebih melekat.",
    tryComprehensiveTitle: "Coba kuis komprehensif level {level}",
    tryComprehensiveDescription: "Mulailah dengan kuis yang mencakup semua kategori untuk melihat posisi Anda saat ini.",
    vocabReviewTitle: "Tinjau ulang daftar kosakata level {level}",
    vocabReviewDescription: "Pelajari kembali {count} kata, dengan fokus pada kata-kata yang belum Anda kuasai.",
    grammarReviewTitle: "Tinjau ulang pola tata bahasa level {level}",
    grammarReviewDescription: "Pelajari kembali {count} pola beserta contoh kalimatnya.",
    levelUpTitle: "Siap melanjutkan ke {level}",
    levelUpDescription: "Akurasi Anda di {current} sudah stabil — coba kuis {level} berikutnya.",
  },
  studyTime: { title: "Waktu belajar", totalLabel: "Total waktu belajar", todayLabel: "Hari ini", weekLabel: "Minggu ini", streakLabel: "Rekor belajar berturut-turut", streakDays: "{days} hari", trendTitle: "Tren waktu belajar (30 hari terakhir)", trendSubtitle: "Menit belajar per hari", minutesUnit: "{minutes} menit", hoursMinutesUnit: "{hours} jam {minutes} menit", noStreak: "Belum ada catatan belajar", noData: "Belum ada waktu belajar yang tercatat. Catatan akan mulai begitu Anda membuka kuis atau daftar kosakata." },
  weakItems: { title: "Kosakata & tata bahasa yang lemah", subtitle: "Item yang sering Anda salah — sebaiknya ditinjau lebih teliti.", vocabTitle: "Kosakata untuk ditinjau", grammarTitle: "Tata bahasa untuk ditinjau", missedCount: "Salah {count} kali", noWeakVocab: "Belum ada kosakata lemah yang teridentifikasi.", noWeakGrammar: "Belum ada tata bahasa lemah yang teridentifikasi." },
  mockExam: { title: "Ujian simulasi", subtitle: "Ujian simulasi yang disusun berdasarkan struktur soal dan kriteria kelulusan JLPT yang sesungguhnya. Anda dapat memilih dan mengikuti ujian dari Edisi 1 hingga Edisi 5.", editionLabel: "Edisi {n}", statusNotTaken: "Belum diikuti", statusPassed: "Lulus", statusFailed: "Tidak lulus", scoreLabel: "{total} / {max} poin", start: "Ikuti ujian", retake: "Ikuti ulang", introTitle: "Ujian Simulasi — Edisi {edition}", introDescription: "Ujian ini mencakup kosakata, tata bahasa, membaca, dan mendengarkan sekaligus, dengan format yang sama seperti JLPT yang sesungguhnya. Saat Anda punya cukup waktu, cobalah mengerjakannya sampai selesai tanpa berhenti di tengah jalan.", introQuestionCount: "Total {count} soal", introSectionsLabel: "Struktur bagian ujian", introSectionKnowledgeReading: "Pengetahuan Bahasa & Membaca", introSectionKnowledge: "Pengetahuan Bahasa (Huruf, Kosakata & Tata Bahasa)", introSectionReading: "Membaca", introSectionListening: "Mendengarkan", introCaveat: "* Penilaian ujian simulasi ini adalah konversi sederhana berdasarkan persentase jawaban benar Anda. JLPT yang sesungguhnya dinilai menggunakan teori respons butir (IRT), sehingga skor dan peluang kelulusan di sini hanya bersifat perkiraan.", startButton: "Mulai ujian", loading: "Memuat soal...", loadFailed: "Gagal memuat soal.", backToLevel: "Kembali ke halaman level", submitting: "Menilai...", submitButton: "Kirim", next: "Berikutnya", resultsTitle: "Hasil ujian simulasi {name}", totalScoreLabel: "Skor total", passResult: "Mencapai batas kelulusan", failResult: "Belum mencapai batas kelulusan", passProbabilityTitle: "Peluang lulus berdasarkan hasil ujian simulasi ini", passProbabilityCaveat: "* Perkiraan ini hanya berdasarkan skor ujian simulasi kali ini (tidak termasuk riwayat kuis biasa Anda).", sectionBreakdownTitle: "Hasil per bagian", sectionScoreLine: "{scaled} / {max} poin (benar {correct}/{total} soal)", sectionPassed: "Mencapai nilai minimum", sectionFailed: "Belum mencapai nilai minimum", sectionMinNote: "Bagian ini mensyaratkan minimal {min} poin untuk lulus.", reviewTitle: "Tinjauan soal", correct: "Benar", incorrect: "Salah", correctAnswer: "Jawaban yang benar: {answer}", backToLevelButton: "Kembali ke halaman level" },
  audio: { playPronunciation: "Putar pelafalan", stopPronunciation: "Berhenti", unsupported: "Browser ini tidak mendukung pemutaran audio." },
};

export default id;
