// Japanese reference dictionary. This is the source of truth: every other
// language file is a translation of this one, and its exact strings match
// what already shipped before i18n existed (so existing "ja" learners see no
// change). ja is also the default/fallback used for account-owner-facing
// pages, which are out of scope for translation.
import type { Dictionary } from "../types";

const ja: Dictionary = {
  category: {
    vocabulary: "語彙",
    grammar: "文法",
    listening: "聴解",
    listeningFull: "聴解（文字起こし）",
    reading: "読解",
  },
  learnerHome: {
    currentLevel: "現在のレベル",
    target: "目標",
    aiAnalysis: "AI分析を見る",
    backToProfiles: "プロフィール選択に戻る",
    aiCoachNote: "AIコーチからのひとこと",
    chooseLevel: "レベルを選ぶ",
    accuracyWithCount: "正答率 {pct}%（{total}問）",
    notAttempted: "未挑戦",
  },
  level: {
    backToHome: "← {name} のホームに戻る",
    levelSuffix: "レベル",
    tryQuiz: "クイズに挑戦",
    questionsCount: "10問に挑戦",
    comprehensiveQuiz: "総合クイズ",
    randomAllCategories: "全カテゴリーからランダム出題",
    vocabListTitle: "語彙リスト（サンプル）",
    grammarListTitle: "文法リスト（サンプル）",
    example: "例：",
  },
  quiz: {
    loading: "問題を読み込んでいます...",
    noQuestionsFound: "この条件のクイズ問題が見つかりませんでした。",
    loadFailed: "問題の読み込みに失敗しました。",
    backToLevel: "レベルページに戻る",
    resultsOf: "{name} さんの結果",
    correct: "正解",
    incorrect: "不正解",
    correctAnswer: "正答: {answer}",
    next: "次へ",
    scoreButton: "採点する",
    scoring: "採点中...",
    aiAnalysis: "AI分析を見る",
  },
  analytics: {
    backToHome: "← {name} のホームに戻る",
    title: "AI進捗分析",
    refresh: "分析を更新",
    refreshing: "更新中...",
    coachAnalysis: "AIコーチの分析",
    lastUpdated: "最終更新: {date}",
    weakStrongTitle: "弱点・得意分野",
    weakStrongSubtitle: "カテゴリー別の正答率",
    paceTitle: "合格可能性・学習ペース予測",
    trendTitle: "学習の推移（直近30日）",
    trendSubtitle: "日ごとの正答率",
    recommendationsTitle: "次のおすすめ学習内容",
  },
  gauge: {
    statusGood: "順調",
    statusWarning: "もう少し",
    statusSerious: "要復習",
    statusCritical: "対策が必要",
    weeksEstimate: "目標到達まで目安 約{weeks}週間。",
  },
  lineChart: {
    noData: "まだ学習記録がありません。クイズに挑戦すると、ここに日ごとの正答率が表示されます。",
    showTable: "表で見る",
    hideTable: "表を隠す",
    tooltipAccuracy: "正答率 {pct}%（{correct}/{attempts}問）",
    colDate: "日付",
    colAttempts: "回答数",
    colCorrect: "正答数",
    colAccuracy: "正答率",
  },
  narrative: {
    noAttempts: "まだクイズの記録がありません。まずはレベルを選んでクイズに挑戦してみましょう。AIが弱点と学習ペースを分析します。",
    summary: "これまでに{total}問に取り組み、正答率は{acc}%です（学習日数: {days}日）。",
    weakest: "特に{category}の正答率が低めなので、重点的に復習するのがおすすめです。",
    strongest: "{category}は好調です。この調子を維持しましょう。",
    paceKnown: "現在のペースでは、{target}到達まで目安で約{weeks}週間、合格可能性は約{pct}%と推定されます。",
    paceUnknown: "学習ペースの予測には、もう少しクイズの記録が必要です。",
  },
  pace: {
    levelReached: "目標レベルに到達済みです。維持のための復習を続けましょう。",
    note: "現在のペースで学習を続けた場合の目安です（信頼度: {confidence}）。",
    needMoreData: "問題演習の記録がまだ少ないため、予測にはあと数回のクイズが必要です。",
    confidenceLow: "低",
    confidenceMedium: "中",
    confidenceHigh: "高",
  },
  recommendations: {
    reviewWeakestTitle: "{category} を重点的に復習",
    reviewWeakestDescription: "直近の正答率は{pct}%です。同じカテゴリーの問題をもう一度解いて定着させましょう。",
    tryComprehensiveTitle: "{level} の総合クイズに挑戦",
    tryComprehensiveDescription: "まずは全カテゴリーのクイズを解いて、現在の実力を測りましょう。",
    vocabReviewTitle: "{level} の語彙リストを復習",
    vocabReviewDescription: "{count}語のうち、まだ自信がない単語を中心に見直しましょう。",
    grammarReviewTitle: "{level} の文法パターンを復習",
    grammarReviewDescription: "{count}個の文型を例文と一緒に確認しましょう。",
    levelUpTitle: "{level} に進む準備ができています",
    levelUpDescription: "{current} の正答率が安定しています。{level} のクイズも試してみましょう。",
  },
};

export default ja;
