import type { Dictionary } from "../types";

const ne: Dictionary = {
  category: { vocabulary: "शब्दावली", grammar: "व्याकरण", listening: "सुनाइ", listeningFull: "सुनाइ (लिपि सहित)", reading: "पढाइ" },
  learnerHome: { currentLevel: "हालको स्तर", target: "लक्ष्य", aiAnalysis: "AI विश्लेषण हेर्नुहोस्", backToProfiles: "प्रोफाइल छनोटमा फर्कनुहोस्", aiCoachNote: "तपाईंको AI कोचबाट सन्देश", chooseLevel: "स्तर छान्नुहोस्", accuracyWithCount: "{pct}% सही ({total} प्रश्न)", notAttempted: "अझै प्रयास गरिएको छैन" },
  level: { backToHome: "← {name}को गृहपृष्ठमा फर्कनुहोस्", levelSuffix: "स्तर", tryQuiz: "क्विज प्रयास गर्नुहोस्", questionsCount: "१० प्रश्नहरू", comprehensiveQuiz: "सम्पूर्ण क्विज", randomAllCategories: "सबै श्रेणीबाट अनियमित प्रश्नहरू", vocabListTitle: "शब्दावली सूची (नमूना)", grammarListTitle: "व्याकरण सूची (नमूना)", example: "उदाहरण:" },
  quiz: { loading: "प्रश्नहरू लोड हुँदैछ...", noQuestionsFound: "यी सेटिङहरूका लागि कुनै क्विज प्रश्न फेला परेन।", loadFailed: "प्रश्नहरू लोड गर्न असफल भयो।", backToLevel: "स्तर पृष्ठमा फर्कनुहोस्", resultsOf: "{name}को नतिजा", correct: "सही", incorrect: "गलत", correctAnswer: "सही उत्तर: {answer}", next: "अर्को", scoreButton: "पेश गर्नुहोस्", scoring: "अंक गणना हुँदैछ...", aiAnalysis: "AI विश्लेषण हेर्नुहोस्" },
  analytics: { backToHome: "← {name}को गृहपृष्ठमा फर्कनुहोस्", title: "AI प्रगति विश्लेषण", refresh: "विश्लेषण ताजा गर्नुहोस्", refreshing: "ताजा गर्दैछ...", coachAnalysis: "AI कोच विश्लेषण", lastUpdated: "पछिल्लो पटक अद्यावधिक: {date}", weakStrongTitle: "कमजोरी र बलियोपन", weakStrongSubtitle: "श्रेणी अनुसार शुद्धता", paceTitle: "उत्तीर्ण हुने सम्भावना र सिकाइको गति", trendTitle: "प्रगति प्रवृत्ति (पछिल्लो ३० दिन)", trendSubtitle: "दैनिक शुद्धता", recommendationsTitle: "अब के अध्ययन गर्ने" },
  gauge: { statusGood: "राम्रो गतिमा", statusWarning: "लगभग पुगिसक्यो", statusSerious: "पुनरावलोकन आवश्यक", statusCritical: "ध्यान दिनु आवश्यक", weeksEstimate: "तपाईंको लक्ष्यमा पुग्न अनुमानित लगभग {weeks} हप्ता लाग्नेछ।" },
  lineChart: { noData: "अझै अध्ययन रेकर्ड छैन। क्विज प्रयास गर्नुहोस् र तपाईंको दैनिक शुद्धता यहाँ देखिनेछ।", showTable: "तालिका देखाउनुहोस्", hideTable: "तालिका लुकाउनुहोस्", tooltipAccuracy: "{pct}% सही ({correct}/{attempts} प्रश्न)", colDate: "मिति", colAttempts: "प्रयासहरू", colCorrect: "सही", colAccuracy: "शुद्धता" },
  narrative: { noAttempts: "अझै कुनै क्विज इतिहास छैन। एउटा स्तर छान्नुहोस् र क्विज प्रयास गर्नुहोस् — तपाईंसँग डेटा भएपछि AI ले तपाईंको कमजोरी र गति विश्लेषण गर्नेछ।", summary: "तपाईंले अहिलेसम्म {total} प्रश्नको जवाफ दिनुभएको छ, {acc}% शुद्धतासहित ({days} दिन सक्रिय)।", weakest: "{category}मा तपाईंको शुद्धता अलि कम छ, त्यसैले पहिले त्यो क्षेत्रको पुनरावलोकन गर्नु राम्रो हुन्छ।", strongest: "तपाईं {category}मा राम्रो गर्दै हुनुहुन्छ — यसै गरी जारी राख्नुहोस्।", paceKnown: "तपाईंको हालको गतिमा, तपाईं लगभग {weeks} हप्तामा {target} पुग्ने अनुमान छ, करिब {pct}% उत्तीर्ण हुने सम्भावनासहित।", paceUnknown: "गति अनुमान गर्नु अघि थप केही क्विजहरू आवश्यक छन्।" },
  pace: { levelReached: "तपाईं पहिले नै आफ्नो लक्ष्य स्तरमा पुगिसक्नुभएको छ। यसलाई कायम राख्न पुनरावलोकन जारी राख्नुहोस्।", note: "यो तपाईंको हालको गतिमा आधारित अनुमान हो (विश्वसनीयता: {confidence})।", needMoreData: "अझै धेरै क्विज इतिहास छैन — भरपर्दो अनुमानका लागि थप केही क्विजहरू आवश्यक छन्।", confidenceLow: "कम", confidenceMedium: "मध्यम", confidenceHigh: "उच्च" },
  recommendations: { reviewWeakestTitle: "{category}को पुनरावलोकनमा ध्यान दिनुहोस्", reviewWeakestDescription: "त्यहाँ तपाईंको हालसालैको शुद्धता {pct}% छ। यो याद राख्न सहयोग गर्न उही श्रेणी फेरि प्रयास गर्नुहोस्।", tryComprehensiveTitle: "{level} सम्पूर्ण क्विज प्रयास गर्नुहोस्", tryComprehensiveDescription: "तपाईं हाल कहाँ हुनुहुन्छ भनी हेर्न सबै श्रेणी समेटिएको क्विजबाट सुरु गर्नुहोस्।", vocabReviewTitle: "{level} शब्दावली सूचीको पुनरावलोकन गर्नुहोस्", vocabReviewDescription: "{count} शब्दहरू हेर्नुहोस्, जुनमा तपाईं कम विश्वस्त हुनुहुन्छ तिनमा ध्यान केन्द्रित गर्दै।", grammarReviewTitle: "{level} व्याकरण ढाँचाहरूको पुनरावलोकन गर्नुहोस्", grammarReviewDescription: "{count} ढाँचाहरू तिनका उदाहरण वाक्यहरूसँगै हेर्नुहोस्।", levelUpTitle: "{level}मा जान तयार", levelUpDescription: "{current}मा तपाईंको शुद्धता स्थिर रहेको छ — अब {level} क्विज प्रयास गर्नुहोस्।" },
};

export default ne;
